
; --------------------
; Layout Portal Tables
; (autogenerated)
; --------------------

; List of vanilla left doors
portals_left_vanilla_table:
    dw $8FA6    ; Alpha Missiles door 0 --> Construction Zone
    dw $8FFA    ; Billy Mays door 0 --> Boulder
    dw $8FE2    ; Boulder door 0 --> Blue Brinstar Energy Tank
    dw $8ECE    ; Construction Zone door 1 --> Blue Brinstar Energy Tank
    dw $8EAA    ; Morph Ball door 1 --> Construction Zone
    dw $9516    ; Grapple Beam door 0 --> Post Crocomire Jump
    dw $9522    ; Grapple Beam door 1 --> Grapple Tutorial 1
    dw $94F2    ; Grapple Tutorial 2 door 1 --> Grapple Tutorial 3
    dw $94C2    ; Grapple Tutorial 3 door 1 --> Post Crocomire Shaft
    dw $9456    ; Post Crocomire Farming door 3 --> Post Crocomire Save
    dw $9432    ; Post Crocomire Farming door 0 --> Crocomire
    dw $946E    ; Post Crocomire Power Bombs door 0 --> Post Crocomire Farming
    dw $9492    ; Post Crocomire Shaft door 2 --> Cosine Missiles
    dw $8C8E    ; 230 Bombway door 1 --> Parlor
    dw $8C9A    ; 230 Missiles door 0 --> 230 Bombway
    dw $8A1E    ; Bowling Alley Path door 1 --> West Ocean Geemer
    dw $ADE8    ; Climb custom door 3 --> Pit
    dw $ADDC    ; Climb custom door 2 --> Climb Supers
    dw $ADD0    ; Climb custom door 1 --> Climb Supers
    dw $8A36    ; Crateria Kihunters door 1 --> Moat
    dw $8AD2    ; Crateria Tube door 1 --> Crateria Kihunters
    dw $8A72    ; East Ocean door 1 --> Forgotten Highway Kago
    dw $8BC2    ; Flyway door 1 --> Bomb Torizo
    dw $8AA2    ; Forgotten Highway Elbow door 0 --> Crab Maze
    dw $8B0E    ; Gauntlet Energy Tank door 0 --> Gauntlet Entrance
    dw $8946    ; Gauntlet Entrance door 0 --> Landing Site
    dw $8BFE    ; Green Brinstar Elevator door 0 --> Lower Mushrooms
    dw $8C52    ; Green Pirates Shaft door 2 --> Statues Hallway
    dw $8C3A    ; Green Pirates Shaft door 0 --> Terminator
    dw $8C5E    ; Green Pirates Shaft door 3 --> Gauntlet Energy Tank
    dw $8922    ; Landing Site door 1 --> Crateria Tube
    dw $8C16    ; Lower Mushrooms door 0 --> Green Pirates Shaft
    dw $8AEA    ; Moat door 1 --> West Ocean
    dw $AD94    ; Parlor custom door 3 --> Flyway
    dw $AD88    ; Parlor custom door 2 --> Pre-Map Flyway
    dw $AD7C    ; Parlor custom door 1 --> Landing Site
    dw $8B86    ; Pit door 1 --> Morph Elevator
    dw $8BDA    ; Pre-Map Flyway door 1 --> Crateria Map Station
    dw $8BF2    ; Terminator door 1 --> Parlor
    dw $89E2    ; West Ocean door 2 --> Bowling Alley Path
    dw $89D6    ; West Ocean door 1 --> Wrecked Ship Entrance
    dw $8A06    ; West Ocean door 5 --> Gravity Suit
    dw $89FA    ; West Ocean door 4 --> Bowling Alley
    dw $89EE    ; West Ocean door 3 --> Attic
    dw $8F16    ; Green Brinstar Beetoms door 0 --> Green Brinstar Main Shaft
    dw $8D8A    ; Green Brinstar Firefleas door 1 --> Green Brinstar Main Shaft
    dw $8D96    ; Brinstar Missile Refill door 0 --> Green Brinstar Firefleas
    dw $8D42    ; Brinstar Pre-Map door 1 --> Green Brinstar Main Shaft
    dw $8D5A    ; Early Supers door 1 --> Brinstar Reserve Tank
    dw $8F46    ; Etecoons Energy Tank door 2 --> Green Brinstar Main Shaft
    dw $8F2E    ; Etecoons Energy Tank door 0 --> Green Brinstar Beetoms
    dw $8F5E    ; Etecoons Supers door 0 --> Etecoons Energy Tank
    dw $8E92    ; Green Hill Zone door 2 --> Noob Bridge
    dw $8E86    ; Green Hill Zone door 1 --> Morph Ball
    dw $8CE2    ; Green Brinstar Main Shaft door 5 --> Dachora
    dw $8CEE    ; Green Brinstar Main Shaft door 6 --> Green Brinstar Main Shaft
    dw $8CD6    ; Green Brinstar Main Shaft door 4 --> Early Supers
    dw $8F0A    ; Noob Bridge door 1 --> Red Tower
    dw $A690    ; East Sand Hall door 1 --> Pants
    dw $A66C    ; Oasis door 1 --> East Sand Hall
    dw $A648    ; West Sand Hall door 1 --> Oasis
    dw $A534    ; West Sand Hall Tunnel door 1 --> West Sand Hall
    dw $919E    ; Baby Kraid door 1 --> Kraid Eye Door
    dw $917A    ; Warehouse Kihunters door 1 --> Baby Kraid
    dw $9186    ; Warehouse Kihunters door 2 --> Warehouse Save
    dw $91C2    ; Kraid Eye Door door 2 --> Kraid Refill
    dw $9162    ; Warehouse Energy Tank door 0 --> Warehouse Zeela
    dw $923A    ; Warehouse Entrance door 1 --> Warehouse Zeela
    dw $9846    ; Acid Statue door 1 --> Main Hall
    dw $989A    ; Fast Rippers door 1 --> Fast Pillars Setup
    dw $9A9E    ; Lower Norfair Firefleas door 1 --> Jail Power Bombs
    dw $9882    ; Golden Torizo door 1 --> Screw Attack
    dw $9A0E    ; Red Kihunter Shaft door 3 --> Red Kihunter Save
    dw $9A02    ; Red Kihunter Shaft door 2 --> Lower Norfair Firefleas
    dw $985E    ; Main Hall door 1 --> Fast Pillars Setup
    dw $9A3E    ; Metal Pirates door 1 --> Wasteland
    dw $9936    ; Mickey Mouse door 1 --> Worst Room In The Game
    dw $994E    ; Pillars door 1 --> Worst Room In The Game
    dw $9912    ; Fast Pillars Setup door 4 --> Pillars
    dw $98EE    ; Fast Pillars Setup door 1 --> Mickey Mouse
    dw $9966    ; Plowerhouse door 1 --> Metal Pirates
    dw $98BE    ; Ridley door 1 --> Lower Norfair Farming
    dw $98D6    ; Lower Norfair Farming door 1 --> Plowerhouse
    dw $9A62    ; Ridley Tank door 0 --> Ridley
    dw $9A7A    ; Screw Attack door 1 --> Golden Torizo Recharge
    dw $9A6E    ; Screw Attack door 0 --> Fast Rippers
    dw $99BA    ; Spring Ball Maze door 1 --> Lower Norfair Firefleas
    dw $9A56    ; Three Musketeers door 1 --> Spring Ball Maze
    dw $997E    ; Worst Room In The Game door 1 --> Amphitheatre
    dw $8DEA    ; Big Pink door 3 --> Green Hill Zone
    dw $8E26    ; Big Pink door 8 --> Spore Spawn Farming
    dw $8E1A    ; Big Pink door 7 --> Pink Brinstar Hoppers
    dw $8DC6    ; Big Pink door 0 --> Spore Spawn Kihunters
    dw $8DAE    ; Dachora door 1 --> Big Pink
    dw $8F6A    ; Dachora Recharge door 0 --> Dachora
    dw $8FBE    ; Pink Brinstar Hoppers door 1 --> Hoppers Energy Tank
    dw $8E62    ; Pink Brinstar Power Bombs door 0 --> Big Pink
    dw $8F76    ; Spore Spawn Farming door 0 --> Spore Spawn Supers
    dw $8F8E    ; Waterway Energy Tank door 0 --> Big Pink
    dw $A738    ; Aqueduct door 4 --> Below Botwoon Energy Tank
    dw $A774    ; Botwoon Hallway door 1 --> Botwoon
    dw $A870    ; Botwoon Energy Tank door 3 --> Halfie Climb
    dw $A7F8    ; Colosseum door 2 --> Precious
    dw $A7EC    ; Colosseum door 1 --> Draygon Save
    dw $A4C8    ; Crab Shaft door 2 --> Aqueduct
    dw $A96C    ; Draygon door 0 --> Precious
    dw $A960    ; East Cactus Alley door 1 --> Halfie Climb
    dw $A8F4    ; Halfie Climb door 2 --> Maridia Missile Refill
    dw $A8E8    ; Halfie Climb door 1 --> Colosseum
    dw $A924    ; Space Jump door 0 --> Draygon
    dw $A948    ; West Cactus Alley door 1 --> East Cactus Alley
    dw $90EA    ; Alpha Power Bombs door 0 --> Caterpillars
    dw $9102    ; Bat door 1 --> Below Spazer
    dw $911A    ; Below Spazer door 1 --> West Tunnel
    dw $9126    ; Below Spazer door 2 --> Spazer
    dw $90DE    ; Beta Power Bombs door 0 --> Caterpillars
    dw $90D2    ; Caterpillars door 6 --> Red Brinstar Save
    dw $90C6    ; Caterpillars door 4 --> Red Fish
    dw $908A    ; Hellway door 1 --> Caterpillars
    dw $9066    ; Red Brinstar Firefleas door 1 --> Red Tower
    dw $9042    ; Red Tower door 3 --> Bat
    dw $901E    ; Red Tower door 0 --> Hellway
    dw $91FE    ; Sloaters Refill door 0 --> Red Tower
    dw $9072    ; X-Ray Scope door 0 --> Red Brinstar Firefleas
    dw $AA38    ; Big Boy door 0 --> Dust Torizo
    dw $A9A8    ; Metroids 1 door 0 --> Tourian First
    dw $A9CC    ; Metroids 2 door 1 --> Metroids 3
    dw $A9C0    ; Metroids 2 door 0 --> Metroids 1
    dw $A9E4    ; Metroids 3 door 1 --> Metroids 4
    dw $AA5C    ; Seaweed door 1 --> Tourian Eye Door
    dw $AA50    ; Seaweed door 0 --> Big Boy
    dw $AE0C    ; Tourian Escape 2 custom door 1 --> Tourian Escape 3
    dw $AE24    ; Tourian Escape 3 custom door 1 --> Tourian Escape 4
    dw $AE3C    ; Tourian Escape 4 custom door 1 --> Climb
    dw $A99C    ; Tourian First door 3 --> Upper Tourian Save
    dw $9756    ; Acid Snakes Tunnel door 1 --> Nutella Refill
    dw $97B6    ; Bat Cave door 1 --> Speed Booster Hall
    dw $9582    ; Bubble Mountain door 4 --> Single Chamber
    dw $958E    ; Bubble Mountain door 5 --> Bat Cave
    dw $92E2    ; Business Center door 3 --> Crocomire Escape
    dw $92FA    ; Business Center door 6 --> Frog Savestation
    dw $92CA    ; Business Center door 1 --> Cathedral Entrance
    dw $929A    ; Cathedral door 1 --> Rising Tide
    dw $92B2    ; Cathedral Entrance door 1 --> Cathedral
    dw $940E    ; Crocomire Escape door 1 --> Crocomire Speedway
    dw $93C6    ; Crocomire Speedway door 3 --> Acid Snakes Tunnel
    dw $93BA    ; Crocomire Speedway door 2 --> Crocomire Save
    dw $9396    ; Crumble Shaft door 1 --> Crocomire Speedway
    dw $938A    ; Crumble Shaft door 0 --> Ice Beam Gate
    dw $961E    ; Double Chamber door 2 --> Wave Beam
    dw $971A    ; Upper Norfair Farming door 1 --> Bubble Mountain
    dw $97E6    ; Frog Speedway door 1 --> Upper Norfair Farming
    dw $953A    ; Green Bubbles Missiles door 0 --> Bubble Mountain
    dw $93F6    ; Hi Jump Boots door 0 --> Hi Jump Energy Tank
    dw $941A    ; Hi Jump Energy Tank door 0 --> Business Center
    dw $9276    ; Ice Beam Acid door 0 --> Ice Beam Gate
    dw $932A    ; Ice Beam Gate door 2 --> Business Center
    dw $9366    ; Ice Beam Snake door 0 --> Ice Beam Acid
    dw $937E    ; Ice Beam Snake door 2 --> Ice Beam
    dw $9372    ; Ice Beam Snake door 1 --> Ice Beam Tutorial
    dw $934E    ; Ice Beam Tutorial door 1 --> Ice Beam Gate
    dw $9672    ; Kronic Boost door 1 --> Volcano
    dw $96D2    ; Lava Dive door 0 --> Kronic Boost
    dw $96EA    ; Lower Norfair Elevator door 0 --> Lava Dive
    dw $96A2    ; Magdollite Tunnel door 1 --> Kronic Boost
    dw $952E    ; Norfair Reserve Tank door 0 --> Green Bubbles Missiles
    dw $9792    ; Nutella Refill door 1 --> Spiky Acid Snakes Tunnel
    dw $973E    ; Rising Tide door 1 --> Bubble Mountain
    dw $96BA    ; Purple Shaft door 1 --> Magdollite Tunnel
    dw $96C6    ; Purple Shaft door 2 --> Purple Farming
    dw $97F2    ; Red Pirates Shaft door 0 --> Upper Norfair Farming
    dw $95FA    ; Single Chamber door 4 --> Three Musketeers
    dw $95EE    ; Single Chamber door 3 --> Spiky Platforms Tunnel
    dw $95E2    ; Single Chamber door 2 --> Double Chamber
    dw $95D6    ; Single Chamber door 1 --> Double Chamber
    dw $95B2    ; Speed Booster Hall door 1 --> Speed Booster
    dw $977A    ; Spiky Acid Snakes Tunnel door 1 --> Kronic Boost
    dw $A51C    ; Crab Hole door 3 --> Maridia Map
    dw $A504    ; Crab Hole door 1 --> West Sand Hall Tunnel
    dw $A420    ; Crab Tunnel door 1 --> Crab Hole
    dw $A384    ; East Tunnel door 1 --> Warehouse Entrance
    dw $A390    ; East Tunnel door 2 --> Crab Hole
    dw $A3E4    ; Fish Tank door 1 --> Mama Turtle
    dw $A354    ; Glass Tunnel door 3 --> Glass Tunnel Save
    dw $A3A8    ; Main Street door 1 --> Crab Tunnel
    dw $A3B4    ; Main Street door 2 --> Fish Tank
    dw $A3C0    ; Main Street door 3 --> Mount Everest
    dw $A468    ; Mount Everest door 5 --> Crab Shaft
    dw $A1D4    ; Attic door 1 --> Assembly Line
    dw $A2AC    ; Basement door 2 --> Phantoon Room
    dw $A264    ; Electric Death door 0 --> East Ocean
    dw $A288    ; Wrecked Ship Energy Tank door 0 --> Electric Death
    dw $A30C    ; Gravity Suit door 1 --> Bowling Alley
    dw $A234    ; Wrecked Ship Main Shaft door 5 --> Wrecked Ship East Supers
    dw $A204    ; Wrecked Ship Main Shaft door 1 --> Sponge Bath
    dw $A240    ; Wrecked Ship Main Shaft door 6 --> Wrecked Ship Save
    dw $A258    ; Spiky Death door 1 --> Electric Death
    dw $A2DC    ; Sponge Bath door 1 --> Spiky Death
    dw $A2E8    ; Wrecked Ship West Supers door 0 --> Wrecked Ship Main Shaft
    dw $A75C    ; Butterfly door 1 --> West Cactus Alley
    dw $A5DC    ; Kassiuz door 1 --> Plasma Tutorial
    dw $A588    ; Maridia Elevator door 1 --> Forgotten Highway Save
    dw $A4A4    ; Northwest Maridia Bugs door 1 --> Pseudo Plasma Spark
    dw $A5A0    ; Plasma Spark door 0 --> Butterfly
    dw $A5C4    ; Plasma Spark door 3 --> Bug Sand Hole
    dw $A5B8    ; Plasma Spark door 2 --> Kassiuz
    dw $A54C    ; Plasma Tutorial door 1 --> Plasma
    dw $A570    ; Thread The Needle door 1 --> Maridia Elevator
    dw $A48C    ; Watering Hole door 0 --> Northwest Maridia Bugs
    dw $893A    ; Landing Site door 3 --> Crateria Power Bombs
    dw $8E4A    ; Spore Spawn door 0 --> Spore Spawn Supers
    dw $A798    ; Pants door 2 --> Shaktool
    dw $A7BC    ; East Pants door 1 --> Shaktool
    dw $A8D0    ; Shaktool door 1 --> Spring Ball
    dw $91DA    ; Kraid door 1 --> Varia Suit
    dw $91B6    ; Kraid Eye Door door 1 --> Kraid
    dw $983A    ; Acid Statue door 0 --> Golden Torizo
    dw $99A2    ; Amphitheatre door 1 --> Red Kihunter Shaft
    dw $8E6E    ; Pink Brinstar Power Bombs door 1 --> Big Pink
    dw $A918    ; Botwoon door 1 --> Botwoon Energy Tank

; Above table with portals inverted
portals_left_vanilla_inverted_table:
    dw $8EDA    ; Construction Zone door 2 --> Alpha Missiles
    dw $8FEE    ; Boulder door 1 --> Billy Mays
    dw $8EF2    ; Blue Brinstar Energy Tank door 1 --> Boulder
    dw $8EE6    ; Blue Brinstar Energy Tank door 0 --> Construction Zone
    dw $8EC2    ; Construction Zone door 0 --> Morph Ball
    dw $94DA    ; Post Crocomire Jump door 1 --> Grapple Beam
    dw $94FE
    dw $94B6    ; Grapple Tutorial 3 door 0 --> Grapple Tutorial 2
    dw $9486    ; Post Crocomire Shaft door 1 --> Grapple Tutorial 3
    dw $9462
    dw $93DE    ; Crocomire door 0 --> Post Crocomire Farming
    dw $943E    ; Post Crocomire Farming door 1 --> Post Crocomire Power Bombs
    dw $94AA    ; Cosine Missiles door 0 --> Post Crocomire Shaft
    dw $ADB8    ; Parlor custom door 6 --> 230 Bombway
    dw $8C82    ; 230 Bombway door 0 --> 230 Missiles
    dw $8B26
    dw $8B7A    ; Pit door 0 --> Climb
    dw $8C76    ; Climb Supers door 1 --> Climb
    dw $8C6A    ; Climb Supers door 0 --> Climb
    dw $8ADE    ; Moat door 0 --> Crateria Kihunters
    dw $8A2A    ; Crateria Kihunters door 0 --> Crateria Tube
    dw $8A7E    ; Forgotten Highway Kago door 0 --> East Ocean
    dw $8BAA    ; Bomb Torizo door 0 --> Flyway
    dw $8AAE    ; Crab Maze door 1 --> Forgotten Highway Elbow
    dw $8952    ; Gauntlet Entrance door 1 --> Gauntlet Energy Tank
    dw $892E    ; Landing Site door 2 --> Gauntlet Entrance
    dw $8C22    ; Lower Mushrooms door 1 --> Green Brinstar Elevator
    dw $91E6
    dw $8BE6    ; Terminator door 0 --> Green Pirates Shaft
    dw $8B1A    ; Gauntlet Energy Tank door 1 --> Green Pirates Shaft
    dw $8AC6    ; Crateria Tube door 0 --> Landing Site
    dw $8C46    ; Green Pirates Shaft door 1 --> Lower Mushrooms
    dw $89CA    ; West Ocean door 0 --> Moat
    dw $8BB6    ; Flyway door 0 --> Parlor
    dw $8BCE    ; Pre-Map Flyway door 0 --> Parlor
    dw $8916    ; Landing Site door 0 --> Parlor
    dw $8B92    ; Morph Elevator door 0 --> Pit
    dw $8C2E
    dw $AD70    ; Parlor custom door 0 --> Terminator
    dw $8A12    ; Bowling Alley Path door 0 --> West Ocean
    dw $A1B0
    dw $A300    ; Gravity Suit door 0 --> West Ocean
    dw $A18C
    dw $A1E0    ; Attic door 2 --> West Ocean
    dw $8CBE    ; Green Brinstar Main Shaft door 2 --> Green Brinstar Beetoms
    dw $8CCA    ; Green Brinstar Main Shaft door 3 --> Green Brinstar Firefleas
    dw $8D7E    ; Green Brinstar Firefleas door 0 --> Brinstar Missile Refill
    dw $8CB2    ; Green Brinstar Main Shaft door 1 --> Brinstar Pre-Map
    dw $8D66    ; Brinstar Reserve Tank door 0 --> Early Supers
    dw $8CFA    ; Green Brinstar Main Shaft door 7 --> Etecoons Energy Tank
    dw $8F22    ; Green Brinstar Beetoms door 1 --> Etecoons Energy Tank
    dw $8F3A    ; Etecoons Energy Tank door 1 --> Etecoons Supers
    dw $8EFE    ; Noob Bridge door 0 --> Green Hill Zone
    dw $8E9E
    dw $8DA2    ; Dachora door 0 --> Green Brinstar Main Shaft
    dw $8D06    ; Green Brinstar Main Shaft door 8 --> Green Brinstar Main Shaft
    dw $8D4E    ; Early Supers door 0 --> Green Brinstar Main Shaft
    dw $902A    ; Red Tower door 1 --> Noob Bridge
    dw $A780    ; Pants door 0 --> East Sand Hall
    dw $A684    ; East Sand Hall door 0 --> Oasis
    dw $A660    ; Oasis door 0 --> West Sand Hall
    dw $A63C    ; West Sand Hall door 0 --> West Sand Hall Tunnel
    dw $91AA    ; Kraid Eye Door door 0 --> Baby Kraid
    dw $9192    ; Baby Kraid door 0 --> Warehouse Kihunters
    dw $925E
    dw $920A    ; Kraid Refill door 0 --> Kraid Eye Door
    dw $914A    ; Warehouse Zeela door 1 --> Warehouse Energy Tank
    dw $913E    ; Warehouse Zeela door 0 --> Warehouse Entrance
    dw $9852    ; Main Hall door 0 --> Acid Statue
    dw $9906    ; Fast Pillars Setup door 3 --> Fast Rippers
    dw $99D2    ; Jail Power Bombs door 0 --> Lower Norfair Firefleas
    dw $9A86    ; Screw Attack door 2 --> Golden Torizo
    dw $9AB6
    dw $9AAA    ; Lower Norfair Firefleas door 2 --> Red Kihunter Shaft
    dw $98E2    ; Fast Pillars Setup door 0 --> Main Hall
    dw $9A1A    ; Wasteland door 0 --> Metal Pirates
    dw $9972    ; Worst Room In The Game door 0 --> Mickey Mouse
    dw $998A    ; Worst Room In The Game door 2 --> Pillars
    dw $9942    ; Pillars door 0 --> Fast Pillars Setup
    dw $992A    ; Mickey Mouse door 0 --> Fast Pillars Setup
    dw $9A32    ; Metal Pirates door 0 --> Plowerhouse
    dw $98CA    ; Lower Norfair Farming door 0 --> Ridley
    dw $995A    ; Plowerhouse door 0 --> Lower Norfair Farming
    dw $98B2    ; Ridley door 0 --> Ridley Tank
    dw $98A6    ; Golden Torizo Recharge door 0 --> Screw Attack
    dw $988E    ; Fast Rippers door 0 --> Screw Attack
    dw $9A92    ; Lower Norfair Firefleas door 0 --> Spring Ball Maze
    dw $99AE    ; Spring Ball Maze door 0 --> Three Musketeers
    dw $9996    ; Amphitheatre door 0 --> Worst Room In The Game
    dw $8E7A    ; Green Hill Zone door 0 --> Big Pink
    dw $8F82    ; Spore Spawn Farming door 1 --> Big Pink
    dw $8FB2    ; Pink Brinstar Hoppers door 0 --> Big Pink
    dw $8E32    ; Spore Spawn Kihunters door 0 --> Big Pink
    dw $8DD2    ; Big Pink door 1 --> Dachora
    dw $8DBA    ; Dachora door 2 --> Dachora Recharge
    dw $8FCA    ; Hoppers Energy Tank door 0 --> Pink Brinstar Hoppers
    dw $8E02
    dw $8D1E    ; Spore Spawn Supers door 0 --> Spore Spawn Farming
    dw $8E0E    ; Big Pink door 6 --> Waterway Energy Tank
    dw $A7D4    ; Below Botwoon Energy Tank door 0 --> Aqueduct
    dw $A90C    ; Botwoon door 0 --> Botwoon Hallway
    dw $A8DC    ; Halfie Climb door 0 --> Botwoon Energy Tank
    dw $A834    ; Precious door 0 --> Colosseum
    dw $A888
    dw $A708    ; Aqueduct door 0 --> Crab Shaft
    dw $A840    ; Precious door 1 --> Draygon
    dw $A900    ; Halfie Climb door 3 --> East Cactus Alley
    dw $A894    ; Maridia Missile Refill door 0 --> Halfie Climb
    dw $A7E0    ; Colosseum door 0 --> Halfie Climb
    dw $A978    ; Draygon door 1 --> Space Jump
    dw $A954    ; East Cactus Alley door 0 --> West Cactus Alley
    dw $9096    ; Caterpillars door 0 --> Alpha Power Bombs
    dw $910E    ; Below Spazer door 0 --> Bat
    dw $A36C
    dw $9132    ; Spazer door 0 --> Below Spazer
    dw $90A2    ; Caterpillars door 1 --> Beta Power Bombs
    dw $926A
    dw $A480    ; Red Fish door 1 --> Caterpillars
    dw $90AE    ; Caterpillars door 2 --> Hellway
    dw $9036    ; Red Tower door 2 --> Red Brinstar Firefleas
    dw $90F6    ; Bat door 0 --> Red Tower
    dw $907E    ; Hellway door 0 --> Red Tower
    dw $904E    ; Red Tower door 4 --> Sloaters Refill
    dw $905A    ; Red Brinstar Firefleas door 0 --> X-Ray Scope
    dw $AA2C
    dw $A984
    dw $A9D8    ; Metroids 3 door 0 --> Metroids 2
    dw $A9B4    ; Metroids 1 door 1 --> Metroids 2
    dw $A9F0    ; Metroids 4 door 0 --> Metroids 3
    dw $AA98
    dw $AA44    ; Big Boy door 1 --> Seaweed
    dw $AB10
    dw $AB28
    dw $8B6E
    dw $AB40
    dw $9786    ; Nutella Refill door 0 --> Acid Snakes Tunnel
    dw $95A6    ; Speed Booster Hall door 0 --> Bat Cave
    dw $95CA    ; Single Chamber door 0 --> Bubble Mountain
    dw $97AA    ; Bat Cave door 0 --> Bubble Mountain
    dw $9402    ; Crocomire Escape door 0 --> Business Center
    dw $9816
    dw $92A6    ; Cathedral Entrance door 0 --> Business Center
    dw $9732    ; Rising Tide door 0 --> Cathedral
    dw $928E    ; Cathedral door 0 --> Cathedral Entrance
    dw $93AE    ; Crocomire Speedway door 1 --> Crocomire Escape
    dw $974A    ; Acid Snakes Tunnel door 0 --> Crocomire Speedway
    dw $9822
    dw $93A2    ; Crocomire Speedway door 0 --> Crumble Shaft
    dw $9336    ; Ice Beam Gate door 3 --> Crumble Shaft
    dw $962A    ; Wave Beam door 0 --> Double Chamber
    dw $956A    ; Bubble Mountain door 2 --> Upper Norfair Farming
    dw $970E    ; Upper Norfair Farming door 0 --> Frog Speedway
    dw $9552    ; Bubble Mountain door 0 --> Green Bubbles Missiles
    dw $9426    ; Hi Jump Energy Tank door 1 --> Hi Jump Boots
    dw $92D6    ; Business Center door 2 --> Hi Jump Energy Tank
    dw $931E    ; Ice Beam Gate door 1 --> Ice Beam Acid
    dw $92BE    ; Business Center door 0 --> Ice Beam Gate
    dw $9282    ; Ice Beam Acid door 1 --> Ice Beam Snake
    dw $935A    ; Ice Beam door 0 --> Ice Beam Snake
    dw $9342    ; Ice Beam Tutorial door 0 --> Ice Beam Snake
    dw $9312    ; Ice Beam Gate door 0 --> Ice Beam Tutorial
    dw $965A    ; Volcano door 1 --> Kronic Boost
    dw $967E    ; Kronic Boost door 2 --> Lava Dive
    dw $96DE    ; Lava Dive door 1 --> Lower Norfair Elevator
    dw $9666    ; Kronic Boost door 0 --> Magdollite Tunnel
    dw $9546    ; Green Bubbles Missiles door 1 --> Norfair Reserve Tank
    dw $976E    ; Spiky Acid Snakes Tunnel door 0 --> Nutella Refill
    dw $955E    ; Bubble Mountain door 1 --> Rising Tide
    dw $9696    ; Magdollite Tunnel door 0 --> Purple Shaft
    dw $979E    ; Purple Farming door 0 --> Purple Shaft
    dw $9726    ; Upper Norfair Farming door 2 --> Red Pirates Shaft
    dw $9A4A    ; Three Musketeers door 0 --> Single Chamber
    dw $9636
    dw $9612    ; Double Chamber door 1 --> Single Chamber
    dw $9606    ; Double Chamber door 0 --> Single Chamber
    dw $95BE    ; Speed Booster door 0 --> Speed Booster Hall
    dw $968A    ; Kronic Boost door 3 --> Spiky Acid Snakes Tunnel
    dw $A5E8
    dw $A528    ; West Sand Hall Tunnel door 0 --> Crab Hole
    dw $A4F8    ; Crab Hole door 0 --> Crab Tunnel
    dw $922E    ; Warehouse Entrance door 0 --> East Tunnel
    dw $A510    ; Crab Hole door 2 --> East Tunnel
    dw $A408    ; Mama Turtle door 1 --> Fish Tank
    dw $A324
    dw $A414    ; Crab Tunnel door 0 --> Main Street
    dw $A3D8    ; Fish Tank door 0 --> Main Street
    dw $A438    ; Mount Everest door 1 --> Main Street
    dw $A4B0    ; Crab Shaft door 0 --> Mount Everest
    dw $A1EC    ; Assembly Line door 0 --> Attic
    dw $A2C4    ; Phantoon Room door 0 --> Basement
    dw $8A66    ; East Ocean door 0 --> Electric Death
    dw $A27C    ; Electric Death door 2 --> Wrecked Ship Energy Tank
    dw $A1A4    ; Bowling Alley door 2 --> Gravity Suit
    dw $A2F4    ; Wrecked Ship East Supers door 0 --> Wrecked Ship Main Shaft
    dw $A2D0    ; Sponge Bath door 0 --> Wrecked Ship Main Shaft
    dw $A318
    dw $A270    ; Electric Death door 1 --> Spiky Death
    dw $A24C    ; Spiky Death door 0 --> Sponge Bath
    dw $A210    ; Wrecked Ship Main Shaft door 2 --> Wrecked Ship West Supers
    dw $A93C    ; West Cactus Alley door 0 --> Butterfly
    dw $A540    ; Plasma Tutorial door 0 --> Kassiuz
    dw $A5F4
    dw $A4D4    ; Pseudo Plasma Spark door 0 --> Northwest Maridia Bugs
    dw $A750    ; Butterfly door 0 --> Plasma Spark
    dw $A630
    dw $A5D0    ; Kassiuz door 0 --> Plasma Spark
    dw $A558    ; Plasma door 0 --> Plasma Tutorial
    dw $A57C    ; Maridia Elevator door 0 --> Thread The Needle
    dw $A498    ; Northwest Maridia Bugs door 0 --> Watering Hole
    dw $89B2    ; Crateria Power Bombs door 0 --> Landing Site
    dw $8D2A    ; Spore Spawn Supers door 1 --> Spore Spawn
    dw $A804
    dw $A8C4    ; Shaktool door 0 --> East Pants
    dw $A7C8    ; Spring Ball door 0 --> Shaktool
    dw $9252    ; Varia Suit door 0 --> Kraid
    dw $91CE    ; Kraid door 0 --> Kraid Eye Door
    dw $9876    ; Golden Torizo door 0 --> Acid Statue
    dw $99F6    ; Red Kihunter Shaft door 1 --> Amphitheatre
    dw $8DDE    ; Big Pink door 2 --> Pink Brinstar Power Bombs
    dw $A84C    ; Botwoon Energy Tank door 0 --> Botwoon

; List of vanilla right doors
portals_right_vanilla_table:
    dw $8FEE    ; Boulder door 1 --> Billy Mays
    dw $8EDA    ; Construction Zone door 2 --> Alpha Missiles
    dw $8EC2    ; Construction Zone door 0 --> Morph Ball
    dw $8EE6    ; Blue Brinstar Energy Tank door 0 --> Construction Zone
    dw $8EF2    ; Blue Brinstar Energy Tank door 1 --> Boulder
    dw $94AA    ; Cosine Missiles door 0 --> Post Crocomire Shaft
    dw $94E6    ; Grapple Tutorial 2 door 0 --> Grapple Tutorial 1
    dw $94B6    ; Grapple Tutorial 3 door 0 --> Grapple Tutorial 2
    dw $943E    ; Post Crocomire Farming door 1 --> Post Crocomire Power Bombs
    dw $94DA    ; Post Crocomire Jump door 1 --> Grapple Beam
    dw $9486    ; Post Crocomire Shaft door 1 --> Grapple Tutorial 3
    dw $8C82    ; 230 Bombway door 0 --> 230 Missiles
    dw $8BAA    ; Bomb Torizo door 0 --> Flyway
    dw $8A12    ; Bowling Alley Path door 0 --> West Ocean
    dw $ADF4    ; Climb custom door 4 --> Tourian Escape 4
    dw $8C76    ; Climb Supers door 1 --> Climb
    dw $8C6A    ; Climb Supers door 0 --> Climb
    dw $8AAE    ; Crab Maze door 1 --> Forgotten Highway Elbow
    dw $8A2A    ; Crateria Kihunters door 0 --> Crateria Tube
    dw $89B2    ; Crateria Power Bombs door 0 --> Landing Site
    dw $8AC6    ; Crateria Tube door 0 --> Landing Site
    dw $8A66    ; East Ocean door 0 --> Electric Death
    dw $8BB6    ; Flyway door 0 --> Parlor
    dw $8A7E    ; Forgotten Highway Kago door 0 --> East Ocean
    dw $8B1A    ; Gauntlet Energy Tank door 1 --> Green Pirates Shaft
    dw $8952    ; Gauntlet Entrance door 1 --> Gauntlet Energy Tank
    dw $8C46    ; Green Pirates Shaft door 1 --> Lower Mushrooms
    dw $8916    ; Landing Site door 0 --> Parlor
    dw $8C22    ; Lower Mushrooms door 1 --> Green Brinstar Elevator
    dw $8ADE    ; Moat door 0 --> Crateria Kihunters
    dw $8B92    ; Morph Elevator door 0 --> Pit
    dw $ADB8    ; Parlor custom door 6 --> 230 Bombway
    dw $ADAC    ; Parlor custom door 5 --> Crateria Save
    dw $AD70    ; Parlor custom door 0 --> Terminator
    dw $8B7A    ; Pit door 0 --> Climb
    dw $8BCE    ; Pre-Map Flyway door 0 --> Parlor
    dw $8BE6    ; Terminator door 0 --> Green Pirates Shaft
    dw $89CA    ; West Ocean door 0 --> Moat
    dw $8F22    ; Green Brinstar Beetoms door 1 --> Etecoons Energy Tank
    dw $8D7E    ; Green Brinstar Firefleas door 0 --> Brinstar Missile Refill
    dw $8D36    ; Brinstar Pre-Map door 0 --> Brinstar Map
    dw $8D66    ; Brinstar Reserve Tank door 0 --> Early Supers
    dw $8D4E    ; Early Supers door 0 --> Green Brinstar Main Shaft
    dw $8F52    ; Etecoons Energy Tank door 3 --> Etecoons Save
    dw $8F3A    ; Etecoons Energy Tank door 1 --> Etecoons Supers
    dw $8E7A    ; Green Hill Zone door 0 --> Big Pink
    dw $8CFA    ; Green Brinstar Main Shaft door 7 --> Etecoons Energy Tank
    dw $8CBE    ; Green Brinstar Main Shaft door 2 --> Green Brinstar Beetoms
    dw $8CCA    ; Green Brinstar Main Shaft door 3 --> Green Brinstar Firefleas
    dw $8D12    ; Green Brinstar Main Shaft door A --> Green Brinstar Main Shaft Save
    dw $8D06    ; Green Brinstar Main Shaft door 8 --> Green Brinstar Main Shaft
    dw $8CB2    ; Green Brinstar Main Shaft door 1 --> Brinstar Pre-Map
    dw $8EFE    ; Noob Bridge door 0 --> Green Hill Zone
    dw $8E32    ; Spore Spawn Kihunters door 0 --> Big Pink
    dw $A684    ; East Sand Hall door 0 --> Oasis
    dw $A660    ; Oasis door 0 --> West Sand Hall
    dw $A780    ; Pants door 0 --> East Sand Hall
    dw $A8C4    ; Shaktool door 0 --> East Pants
    dw $A7C8    ; Spring Ball door 0 --> Shaktool
    dw $A63C    ; West Sand Hall door 0 --> West Sand Hall Tunnel
    dw $A528    ; West Sand Hall Tunnel door 0 --> Crab Hole
    dw $9192    ; Baby Kraid door 0 --> Warehouse Kihunters
    dw $91CE    ; Kraid door 0 --> Kraid Eye Door
    dw $91AA    ; Kraid Eye Door door 0 --> Baby Kraid
    dw $920A    ; Kraid Refill door 0 --> Kraid Eye Door
    dw $9252    ; Varia Suit door 0 --> Kraid
    dw $922E    ; Warehouse Entrance door 0 --> East Tunnel
    dw $914A    ; Warehouse Zeela door 1 --> Warehouse Energy Tank
    dw $913E    ; Warehouse Zeela door 0 --> Warehouse Entrance
    dw $9996    ; Amphitheatre door 0 --> Worst Room In The Game
    dw $988E    ; Fast Rippers door 0 --> Screw Attack
    dw $9AAA    ; Lower Norfair Firefleas door 2 --> Red Kihunter Shaft
    dw $9A92    ; Lower Norfair Firefleas door 0 --> Spring Ball Maze
    dw $9876    ; Golden Torizo door 0 --> Acid Statue
    dw $98A6    ; Golden Torizo Recharge door 0 --> Screw Attack
    dw $99D2    ; Jail Power Bombs door 0 --> Lower Norfair Firefleas
    dw $99F6    ; Red Kihunter Shaft door 1 --> Amphitheatre
    dw $9852    ; Main Hall door 0 --> Acid Statue
    dw $9A32    ; Metal Pirates door 0 --> Plowerhouse
    dw $992A    ; Mickey Mouse door 0 --> Fast Pillars Setup
    dw $9942    ; Pillars door 0 --> Fast Pillars Setup
    dw $9906    ; Fast Pillars Setup door 3 --> Fast Rippers
    dw $98E2    ; Fast Pillars Setup door 0 --> Main Hall
    dw $995A    ; Plowerhouse door 0 --> Lower Norfair Farming
    dw $98B2    ; Ridley door 0 --> Ridley Tank
    dw $98CA    ; Lower Norfair Farming door 0 --> Ridley
    dw $9A86    ; Screw Attack door 2 --> Golden Torizo
    dw $99AE    ; Spring Ball Maze door 0 --> Three Musketeers
    dw $9A4A    ; Three Musketeers door 0 --> Single Chamber
    dw $9A1A    ; Wasteland door 0 --> Metal Pirates
    dw $998A    ; Worst Room In The Game door 2 --> Pillars
    dw $9972    ; Worst Room In The Game door 0 --> Mickey Mouse
    dw $8E0E    ; Big Pink door 6 --> Waterway Energy Tank
    dw $8DDE    ; Big Pink door 2 --> Pink Brinstar Power Bombs
    dw $8DD2    ; Big Pink door 1 --> Dachora
    dw $8DF6    ; Big Pink door 4 --> Big Pink Save
    dw $8DBA    ; Dachora door 2 --> Dachora Recharge
    dw $8DA2    ; Dachora door 0 --> Green Brinstar Main Shaft
    dw $8FB2    ; Pink Brinstar Hoppers door 0 --> Big Pink
    dw $8FCA    ; Hoppers Energy Tank door 0 --> Pink Brinstar Hoppers
    dw $8F82    ; Spore Spawn Farming door 1 --> Big Pink
    dw $8D1E    ; Spore Spawn Supers door 0 --> Spore Spawn Farming
    dw $8D2A    ; Spore Spawn Supers door 1 --> Spore Spawn
    dw $A744    ; Aqueduct door 5 --> Aqueduct Save
    dw $A708    ; Aqueduct door 0 --> Crab Shaft
    dw $A7D4    ; Below Botwoon Energy Tank door 0 --> Aqueduct
    dw $A90C    ; Botwoon door 0 --> Botwoon Hallway
    dw $A84C    ; Botwoon Energy Tank door 0 --> Botwoon
    dw $A7E0    ; Colosseum door 0 --> Halfie Climb
    dw $A4B0    ; Crab Shaft door 0 --> Mount Everest
    dw $A978    ; Draygon door 1 --> Space Jump
    dw $A954    ; East Cactus Alley door 0 --> West Cactus Alley
    dw $A8DC    ; Halfie Climb door 0 --> Botwoon Energy Tank
    dw $A900    ; Halfie Climb door 3 --> East Cactus Alley
    dw $A894    ; Maridia Missile Refill door 0 --> Halfie Climb
    dw $A840    ; Precious door 1 --> Draygon
    dw $A834    ; Precious door 0 --> Colosseum
    dw $A93C    ; West Cactus Alley door 0 --> Butterfly
    dw $90F6    ; Bat door 0 --> Red Tower
    dw $910E    ; Below Spazer door 0 --> Bat
    dw $9096    ; Caterpillars door 0 --> Alpha Power Bombs
    dw $90AE    ; Caterpillars door 2 --> Hellway
    dw $90A2    ; Caterpillars door 1 --> Beta Power Bombs
    dw $907E    ; Hellway door 0 --> Red Tower
    dw $905A    ; Red Brinstar Firefleas door 0 --> X-Ray Scope
    dw $904E    ; Red Tower door 4 --> Sloaters Refill
    dw $9036    ; Red Tower door 2 --> Red Brinstar Firefleas
    dw $902A    ; Red Tower door 1 --> Noob Bridge
    dw $9132    ; Spazer door 0 --> Below Spazer
    dw $A9B4    ; Metroids 1 door 1 --> Metroids 2
    dw $A9D8    ; Metroids 3 door 0 --> Metroids 2
    dw $A9F0    ; Metroids 4 door 0 --> Metroids 3
    dw $AE60    ; Statues custom door 0 --> Statues Hallway
    dw $AAC8    ; Rinka Shaft door 2 --> Mother Brain
    dw $AABC    ; Rinka Shaft door 1 --> Lower Tourian Save
    dw $AA68    ; Seaweed door 2 --> Tourian Recharge
    dw $AE18    ; Tourian Escape 3 custom door 0 --> Tourian Escape 2
    dw $AE30    ; Tourian Escape 4 custom door 0 --> Tourian Escape 3
    dw $974A    ; Acid Snakes Tunnel door 0 --> Crocomire Speedway
    dw $97AA    ; Bat Cave door 0 --> Bubble Mountain
    dw $956A    ; Bubble Mountain door 2 --> Upper Norfair Farming
    dw $955E    ; Bubble Mountain door 1 --> Rising Tide
    dw $959A    ; Bubble Mountain door 6 --> Bubble Mountain Save
    dw $9552    ; Bubble Mountain door 0 --> Green Bubbles Missiles
    dw $92D6    ; Business Center door 2 --> Hi Jump Energy Tank
    dw $9306    ; Business Center door 7 --> Norfair Map
    dw $92BE    ; Business Center door 0 --> Ice Beam Gate
    dw $928E    ; Cathedral door 0 --> Cathedral Entrance
    dw $92A6    ; Cathedral Entrance door 0 --> Business Center
    dw $9402    ; Crocomire Escape door 0 --> Business Center
    dw $93A2    ; Crocomire Speedway door 0 --> Crumble Shaft
    dw $93AE    ; Crocomire Speedway door 1 --> Crocomire Escape
    dw $9612    ; Double Chamber door 1 --> Single Chamber
    dw $9606    ; Double Chamber door 0 --> Single Chamber
    dw $9726    ; Upper Norfair Farming door 2 --> Red Pirates Shaft
    dw $970E    ; Upper Norfair Farming door 0 --> Frog Speedway
    dw $97DA    ; Frog Speedway door 0 --> Frog Savestation
    dw $9546    ; Green Bubbles Missiles door 1 --> Norfair Reserve Tank
    dw $9426    ; Hi Jump Energy Tank door 1 --> Hi Jump Boots
    dw $935A    ; Ice Beam door 0 --> Ice Beam Snake
    dw $9282    ; Ice Beam Acid door 1 --> Ice Beam Snake
    dw $9336    ; Ice Beam Gate door 3 --> Crumble Shaft
    dw $931E    ; Ice Beam Gate door 1 --> Ice Beam Acid
    dw $9312    ; Ice Beam Gate door 0 --> Ice Beam Tutorial
    dw $9342    ; Ice Beam Tutorial door 0 --> Ice Beam Snake
    dw $967E    ; Kronic Boost door 2 --> Lava Dive
    dw $968A    ; Kronic Boost door 3 --> Spiky Acid Snakes Tunnel
    dw $9666    ; Kronic Boost door 0 --> Magdollite Tunnel
    dw $96DE    ; Lava Dive door 1 --> Lower Norfair Elevator
    dw $9702    ; Lower Norfair Elevator door 3 --> Lower Norfair Elevator Save
    dw $9696    ; Magdollite Tunnel door 0 --> Purple Shaft
    dw $9786    ; Nutella Refill door 0 --> Acid Snakes Tunnel
    dw $979E    ; Purple Farming door 0 --> Purple Shaft
    dw $9732    ; Rising Tide door 0 --> Cathedral
    dw $95CA    ; Single Chamber door 0 --> Bubble Mountain
    dw $95BE    ; Speed Booster door 0 --> Speed Booster Hall
    dw $95A6    ; Speed Booster Hall door 0 --> Bat Cave
    dw $976E    ; Spiky Acid Snakes Tunnel door 0 --> Nutella Refill
    dw $965A    ; Volcano door 1 --> Kronic Boost
    dw $964E    ; Volcano door 0 --> Spiky Platforms Tunnel
    dw $962A    ; Wave Beam door 0 --> Double Chamber
    dw $A510    ; Crab Hole door 2 --> East Tunnel
    dw $A4F8    ; Crab Hole door 0 --> Crab Tunnel
    dw $A414    ; Crab Tunnel door 0 --> Main Street
    dw $A378    ; East Tunnel door 0 --> Glass Tunnel
    dw $A3D8    ; Fish Tank door 0 --> Main Street
    dw $A408    ; Mama Turtle door 1 --> Fish Tank
    dw $A438    ; Mount Everest door 1 --> Main Street
    dw $A480    ; Red Fish door 1 --> Caterpillars
    dw $A1EC    ; Assembly Line door 0 --> Attic
    dw $A1E0    ; Attic door 2 --> West Ocean
    dw $A2A0    ; Basement door 1 --> Wrecked Ship Map
    dw $A198    ; Bowling Alley door 1 --> West Ocean Geemer
    dw $A2F4    ; Wrecked Ship East Supers door 0 --> Wrecked Ship Main Shaft
    dw $A270    ; Electric Death door 1 --> Spiky Death
    dw $A27C    ; Electric Death door 2 --> Wrecked Ship Energy Tank
    dw $A300    ; Gravity Suit door 0 --> West Ocean
    dw $A210    ; Wrecked Ship Main Shaft door 2 --> Wrecked Ship West Supers
    dw $A1F8    ; Wrecked Ship Main Shaft door 0 --> Wrecked Ship Entrance
    dw $A2C4    ; Phantoon Room door 0 --> Basement
    dw $A24C    ; Spiky Death door 0 --> Sponge Bath
    dw $A2D0    ; Sponge Bath door 0 --> Wrecked Ship Main Shaft
    dw $A750    ; Butterfly door 0 --> Plasma Spark
    dw $A5D0    ; Kassiuz door 0 --> Plasma Spark
    dw $A57C    ; Maridia Elevator door 0 --> Thread The Needle
    dw $A498    ; Northwest Maridia Bugs door 0 --> Watering Hole
    dw $A558    ; Plasma door 0 --> Plasma Tutorial
    dw $A540    ; Plasma Tutorial door 0 --> Kassiuz
    dw $A4D4    ; Pseudo Plasma Spark door 0 --> Northwest Maridia Bugs
    dw $A564    ; Thread The Needle door 0 --> Bug Sand Hole
    dw $93DE    ; Crocomire door 0 --> Post Crocomire Farming
    dw $892E    ; Landing Site door 2 --> Gauntlet Entrance
    dw $AA44    ; Big Boy door 1 --> Seaweed
    dw $AA14    ; Blue Hoppers door 1 --> Dust Torizo
    dw $AAB0    ; Rinka Shaft door 0 --> Tourian Eye Door
    dw $A1A4    ; Bowling Alley door 2 --> Gravity Suit

; Above table with portals inverted
portals_right_vanilla_inverted_table:
    dw $8FFA    ; Billy Mays door 0 --> Boulder
    dw $8FA6    ; Alpha Missiles door 0 --> Construction Zone
    dw $8EAA    ; Morph Ball door 1 --> Construction Zone
    dw $8ECE    ; Construction Zone door 1 --> Blue Brinstar Energy Tank
    dw $8FE2    ; Boulder door 0 --> Blue Brinstar Energy Tank
    dw $9492    ; Post Crocomire Shaft door 2 --> Cosine Missiles
    dw $950A
    dw $94F2    ; Grapple Tutorial 2 door 1 --> Grapple Tutorial 3
    dw $946E    ; Post Crocomire Power Bombs door 0 --> Post Crocomire Farming
    dw $9516    ; Grapple Beam door 0 --> Post Crocomire Jump
    dw $94C2    ; Grapple Tutorial 3 door 1 --> Post Crocomire Shaft
    dw $8C9A    ; 230 Missiles door 0 --> 230 Bombway
    dw $8BC2    ; Flyway door 1 --> Bomb Torizo
    dw $89E2    ; West Ocean door 2 --> Bowling Alley Path
    dw $AB34
    dw $ADDC    ; Climb custom door 2 --> Climb Supers
    dw $ADD0    ; Climb custom door 1 --> Climb Supers
    dw $8AA2    ; Forgotten Highway Elbow door 0 --> Crab Maze
    dw $8AD2    ; Crateria Tube door 1 --> Crateria Kihunters
    dw $893A    ; Landing Site door 3 --> Crateria Power Bombs
    dw $8922    ; Landing Site door 1 --> Crateria Tube
    dw $A264    ; Electric Death door 0 --> East Ocean
    dw $AD94    ; Parlor custom door 3 --> Flyway
    dw $8A72    ; East Ocean door 1 --> Forgotten Highway Kago
    dw $8C5E    ; Green Pirates Shaft door 3 --> Gauntlet Energy Tank
    dw $8B0E    ; Gauntlet Energy Tank door 0 --> Gauntlet Entrance
    dw $8C16    ; Lower Mushrooms door 0 --> Green Pirates Shaft
    dw $AD7C    ; Parlor custom door 1 --> Landing Site
    dw $8BFE    ; Green Brinstar Elevator door 0 --> Lower Mushrooms
    dw $8A36    ; Crateria Kihunters door 1 --> Moat
    dw $8B86    ; Pit door 1 --> Morph Elevator
    dw $8C8E    ; 230 Bombway door 1 --> Parlor
    dw $89BE
    dw $8BF2    ; Terminator door 1 --> Parlor
    dw $ADE8    ; Climb custom door 3 --> Pit
    dw $AD88    ; Parlor custom door 2 --> Pre-Map Flyway
    dw $8C3A    ; Green Pirates Shaft door 0 --> Terminator
    dw $8AEA    ; Moat door 1 --> West Ocean
    dw $8F2E    ; Etecoons Energy Tank door 0 --> Green Brinstar Beetoms
    dw $8D96    ; Brinstar Missile Refill door 0 --> Green Brinstar Firefleas
    dw $8D72
    dw $8D5A    ; Early Supers door 1 --> Brinstar Reserve Tank
    dw $8CD6    ; Green Brinstar Main Shaft door 4 --> Early Supers
    dw $9012
    dw $8F5E    ; Etecoons Supers door 0 --> Etecoons Energy Tank
    dw $8DEA    ; Big Pink door 3 --> Green Hill Zone
    dw $8F46    ; Etecoons Energy Tank door 2 --> Green Brinstar Main Shaft
    dw $8F16    ; Green Brinstar Beetoms door 0 --> Green Brinstar Main Shaft
    dw $8D8A    ; Green Brinstar Firefleas door 1 --> Green Brinstar Main Shaft
    dw $9006
    dw $8CEE    ; Green Brinstar Main Shaft door 6 --> Green Brinstar Main Shaft
    dw $8D42    ; Brinstar Pre-Map door 1 --> Green Brinstar Main Shaft
    dw $8E92    ; Green Hill Zone door 2 --> Noob Bridge
    dw $8DC6    ; Big Pink door 0 --> Spore Spawn Kihunters
    dw $A66C    ; Oasis door 1 --> East Sand Hall
    dw $A648    ; West Sand Hall door 1 --> Oasis
    dw $A690    ; East Sand Hall door 1 --> Pants
    dw $A7BC    ; East Pants door 1 --> Shaktool
    dw $A8D0    ; Shaktool door 1 --> Spring Ball
    dw $A534    ; West Sand Hall Tunnel door 1 --> West Sand Hall
    dw $A504    ; Crab Hole door 1 --> West Sand Hall Tunnel
    dw $917A    ; Warehouse Kihunters door 1 --> Baby Kraid
    dw $91B6    ; Kraid Eye Door door 1 --> Kraid
    dw $919E    ; Baby Kraid door 1 --> Kraid Eye Door
    dw $91C2    ; Kraid Eye Door door 2 --> Kraid Refill
    dw $91DA    ; Kraid door 1 --> Varia Suit
    dw $A384    ; East Tunnel door 1 --> Warehouse Entrance
    dw $9162    ; Warehouse Energy Tank door 0 --> Warehouse Zeela
    dw $923A    ; Warehouse Entrance door 1 --> Warehouse Zeela
    dw $997E    ; Worst Room In The Game door 1 --> Amphitheatre
    dw $9A6E    ; Screw Attack door 0 --> Fast Rippers
    dw $9A02    ; Red Kihunter Shaft door 2 --> Lower Norfair Firefleas
    dw $99BA    ; Spring Ball Maze door 1 --> Lower Norfair Firefleas
    dw $983A    ; Acid Statue door 0 --> Golden Torizo
    dw $9A7A    ; Screw Attack door 1 --> Golden Torizo Recharge
    dw $9A9E    ; Lower Norfair Firefleas door 1 --> Jail Power Bombs
    dw $99A2    ; Amphitheatre door 1 --> Red Kihunter Shaft
    dw $9846    ; Acid Statue door 1 --> Main Hall
    dw $9966    ; Plowerhouse door 1 --> Metal Pirates
    dw $98EE    ; Fast Pillars Setup door 1 --> Mickey Mouse
    dw $9912    ; Fast Pillars Setup door 4 --> Pillars
    dw $989A    ; Fast Rippers door 1 --> Fast Pillars Setup
    dw $985E    ; Main Hall door 1 --> Fast Pillars Setup
    dw $98D6    ; Lower Norfair Farming door 1 --> Plowerhouse
    dw $9A62    ; Ridley Tank door 0 --> Ridley
    dw $98BE    ; Ridley door 1 --> Lower Norfair Farming
    dw $9882    ; Golden Torizo door 1 --> Screw Attack
    dw $9A56    ; Three Musketeers door 1 --> Spring Ball Maze
    dw $95FA    ; Single Chamber door 4 --> Three Musketeers
    dw $9A3E    ; Metal Pirates door 1 --> Wasteland
    dw $994E    ; Pillars door 1 --> Worst Room In The Game
    dw $9936    ; Mickey Mouse door 1 --> Worst Room In The Game
    dw $8F8E    ; Waterway Energy Tank door 0 --> Big Pink
    dw $8E6E    ; Pink Brinstar Power Bombs door 1 --> Big Pink
    dw $8DAE    ; Dachora door 1 --> Big Pink
    dw $8FD6
    dw $8F6A    ; Dachora Recharge door 0 --> Dachora
    dw $8CE2    ; Green Brinstar Main Shaft door 5 --> Dachora
    dw $8E1A    ; Big Pink door 7 --> Pink Brinstar Hoppers
    dw $8FBE    ; Pink Brinstar Hoppers door 1 --> Hoppers Energy Tank
    dw $8E26    ; Big Pink door 8 --> Spore Spawn Farming
    dw $8F76    ; Spore Spawn Farming door 0 --> Spore Spawn Supers
    dw $8E4A    ; Spore Spawn door 0 --> Spore Spawn Supers
    dw $A828
    dw $A4C8    ; Crab Shaft door 2 --> Aqueduct
    dw $A738    ; Aqueduct door 4 --> Below Botwoon Energy Tank
    dw $A774    ; Botwoon Hallway door 1 --> Botwoon
    dw $A918    ; Botwoon door 1 --> Botwoon Energy Tank
    dw $A8E8    ; Halfie Climb door 1 --> Colosseum
    dw $A468    ; Mount Everest door 5 --> Crab Shaft
    dw $A924    ; Space Jump door 0 --> Draygon
    dw $A948    ; West Cactus Alley door 1 --> East Cactus Alley
    dw $A870    ; Botwoon Energy Tank door 3 --> Halfie Climb
    dw $A960    ; East Cactus Alley door 1 --> Halfie Climb
    dw $A8F4    ; Halfie Climb door 2 --> Maridia Missile Refill
    dw $A96C    ; Draygon door 0 --> Precious
    dw $A7F8    ; Colosseum door 2 --> Precious
    dw $A75C    ; Butterfly door 1 --> West Cactus Alley
    dw $9042    ; Red Tower door 3 --> Bat
    dw $9102    ; Bat door 1 --> Below Spazer
    dw $90EA    ; Alpha Power Bombs door 0 --> Caterpillars
    dw $908A    ; Hellway door 1 --> Caterpillars
    dw $90DE    ; Beta Power Bombs door 0 --> Caterpillars
    dw $901E    ; Red Tower door 0 --> Hellway
    dw $9072    ; X-Ray Scope door 0 --> Red Brinstar Firefleas
    dw $91FE    ; Sloaters Refill door 0 --> Red Tower
    dw $9066    ; Red Brinstar Firefleas door 1 --> Red Tower
    dw $8F0A    ; Noob Bridge door 1 --> Red Tower
    dw $9126    ; Below Spazer door 2 --> Spazer
    dw $A9C0    ; Metroids 2 door 0 --> Metroids 1
    dw $A9CC    ; Metroids 2 door 1 --> Metroids 3
    dw $A9E4    ; Metroids 3 door 1 --> Metroids 4
    dw $91F2
    dw $AA80
    dw $AAD4
    dw $AA74
    dw $AB04
    dw $AB1C
    dw $93C6    ; Crocomire Speedway door 3 --> Acid Snakes Tunnel
    dw $958E    ; Bubble Mountain door 5 --> Bat Cave
    dw $971A    ; Upper Norfair Farming door 1 --> Bubble Mountain
    dw $973E    ; Rising Tide door 1 --> Bubble Mountain
    dw $97CE
    dw $953A    ; Green Bubbles Missiles door 0 --> Bubble Mountain
    dw $941A    ; Hi Jump Energy Tank door 0 --> Business Center
    dw $97C2
    dw $932A    ; Ice Beam Gate door 2 --> Business Center
    dw $92B2    ; Cathedral Entrance door 1 --> Cathedral
    dw $92CA    ; Business Center door 1 --> Cathedral Entrance
    dw $92E2    ; Business Center door 3 --> Crocomire Escape
    dw $9396    ; Crumble Shaft door 1 --> Crocomire Speedway
    dw $940E    ; Crocomire Escape door 1 --> Crocomire Speedway
    dw $95E2    ; Single Chamber door 2 --> Double Chamber
    dw $95D6    ; Single Chamber door 1 --> Double Chamber
    dw $97F2    ; Red Pirates Shaft door 0 --> Upper Norfair Farming
    dw $97E6    ; Frog Speedway door 1 --> Upper Norfair Farming
    dw $980A
    dw $952E    ; Norfair Reserve Tank door 0 --> Green Bubbles Missiles
    dw $93F6    ; Hi Jump Boots door 0 --> Hi Jump Energy Tank
    dw $937E    ; Ice Beam Snake door 2 --> Ice Beam
    dw $9366    ; Ice Beam Snake door 0 --> Ice Beam Acid
    dw $938A    ; Crumble Shaft door 0 --> Ice Beam Gate
    dw $9276    ; Ice Beam Acid door 0 --> Ice Beam Gate
    dw $934E    ; Ice Beam Tutorial door 1 --> Ice Beam Gate
    dw $9372    ; Ice Beam Snake door 1 --> Ice Beam Tutorial
    dw $96D2    ; Lava Dive door 0 --> Kronic Boost
    dw $977A    ; Spiky Acid Snakes Tunnel door 1 --> Kronic Boost
    dw $96A2    ; Magdollite Tunnel door 1 --> Kronic Boost
    dw $96EA    ; Lower Norfair Elevator door 0 --> Lava Dive
    dw $982E
    dw $96BA    ; Purple Shaft door 1 --> Magdollite Tunnel
    dw $9756    ; Acid Snakes Tunnel door 1 --> Nutella Refill
    dw $96C6    ; Purple Shaft door 2 --> Purple Farming
    dw $929A    ; Cathedral door 1 --> Rising Tide
    dw $9582    ; Bubble Mountain door 4 --> Single Chamber
    dw $95B2    ; Speed Booster Hall door 1 --> Speed Booster
    dw $97B6    ; Bat Cave door 1 --> Speed Booster Hall
    dw $9792    ; Nutella Refill door 1 --> Spiky Acid Snakes Tunnel
    dw $9672    ; Kronic Boost door 1 --> Volcano
    dw $9642
    dw $961E    ; Double Chamber door 2 --> Wave Beam
    dw $A390    ; East Tunnel door 2 --> Crab Hole
    dw $A420    ; Crab Tunnel door 1 --> Crab Hole
    dw $A3A8    ; Main Street door 1 --> Crab Tunnel
    dw $A348
    dw $A3B4    ; Main Street door 2 --> Fish Tank
    dw $A3E4    ; Fish Tank door 1 --> Mama Turtle
    dw $A3C0    ; Main Street door 3 --> Mount Everest
    dw $90C6    ; Caterpillars door 4 --> Red Fish
    dw $A1D4    ; Attic door 1 --> Assembly Line
    dw $89EE    ; West Ocean door 3 --> Attic
    dw $A2B8
    dw $8B32
    dw $A234    ; Wrecked Ship Main Shaft door 5 --> Wrecked Ship East Supers
    dw $A258    ; Spiky Death door 1 --> Electric Death
    dw $A288    ; Wrecked Ship Energy Tank door 0 --> Electric Death
    dw $8A06    ; West Ocean door 5 --> Gravity Suit
    dw $A2E8    ; Wrecked Ship West Supers door 0 --> Wrecked Ship Main Shaft
    dw $A1BC
    dw $A2AC    ; Basement door 2 --> Phantoon Room
    dw $A2DC    ; Sponge Bath door 1 --> Spiky Death
    dw $A204    ; Wrecked Ship Main Shaft door 1 --> Sponge Bath
    dw $A5A0    ; Plasma Spark door 0 --> Butterfly
    dw $A5B8    ; Plasma Spark door 2 --> Kassiuz
    dw $A570    ; Thread The Needle door 1 --> Maridia Elevator
    dw $A48C    ; Watering Hole door 0 --> Northwest Maridia Bugs
    dw $A54C    ; Plasma Tutorial door 1 --> Plasma
    dw $A5DC    ; Kassiuz door 1 --> Plasma Tutorial
    dw $A4A4    ; Northwest Maridia Bugs door 1 --> Pseudo Plasma Spark
    dw $A618
    dw $9432    ; Post Crocomire Farming door 0 --> Crocomire
    dw $8946    ; Gauntlet Entrance door 0 --> Landing Site
    dw $AA50    ; Seaweed door 0 --> Big Boy
    dw $AA20
    dw $AAA4
    dw $A30C    ; Gravity Suit door 1 --> Bowling Alley

; List of vanilla up doors
portals_up_vanilla_table:
    dw $944A    ; Post Crocomire Farming door 2 --> Post Crocomire Shaft
    dw $949E    ; Post Crocomire Shaft door 3 --> Post Crocomire Jump
    dw $8A42    ; Crateria Kihunters door 2 --> Red Brinstar Elevator
    dw $8ABA    ; Forgotten Highway Elbow door 1 --> Forgotten Highway Elevator
    dw $8A8A    ; Forgotten Highway Kago door 1 --> Crab Maze
    dw $ADA0    ; Parlor custom door 4 --> Climb
    dw $8E56    ; Spore Spawn door 1 --> Spore Spawn Kihunters
    dw $916E    ; Warehouse Kihunters door 0 --> Warehouse Zeela
    dw $99EA    ; Red Kihunter Shaft door 0 --> Wasteland
    dw $99C6    ; Spring Ball Maze door 2 --> Jail Power Bombs
    dw $A768    ; Botwoon Hallway door 0 --> Aqueduct
    dw $A6CC    ; East Sand Hole door 1 --> East Sand Hall
    dw $A6B4    ; West Sand Hole door 1 --> West Sand Hall
    dw $A9FC    ; Metroids 4 door 1 --> Blue Hoppers
    dw $9576    ; Bubble Mountain door 3 --> Purple Shaft
    dw $93D2    ; Crocomire Speedway door 4 --> Crocomire
    dw $97FE    ; Red Pirates Shaft door 1 --> Acid Snakes Tunnel
    dw $A39C    ; Main Street door 0 --> Glass Tunnel
    dw $A444    ; Mount Everest door 2 --> Fish Tank
    dw $A450    ; Mount Everest door 3 --> Fish Tank
    dw $A474    ; Red Fish door 0 --> Mount Everest
    dw $A1C8    ; Attic door 0 --> Wrecked Ship Main Shaft
    dw $A21C    ; Wrecked Ship Main Shaft door 3 --> Basement
    dw $A5AC    ; Plasma Spark door 1 --> Aqueduct Tube
    dw $A4E0    ; Pseudo Plasma Spark door 1 --> Crab Shaft
    dw $AAEC    ; Tourian Escape 1 door 1 --> Tourian Escape 2

; Above table with portals inverted
portals_up_vanilla_inverted_table:
    dw $947A    ; Post Crocomire Shaft door 0 --> Post Crocomire Farming
    dw $94CE    ; Post Crocomire Jump door 0 --> Post Crocomire Shaft
    dw $8AF6    ; Red Brinstar Elevator door 0 --> Crateria Kihunters
    dw $8A4E    ; Forgotten Highway Elevator door 0 --> Forgotten Highway Elbow
    dw $8A96    ; Crab Maze door 0 --> Forgotten Highway Kago
    dw $8B3E
    dw $8E3E    ; Spore Spawn Kihunters door 1 --> Spore Spawn
    dw $9156    ; Warehouse Zeela door 2 --> Warehouse Kihunters
    dw $9A26    ; Wasteland door 1 --> Red Kihunter Shaft
    dw $99DE    ; Jail Power Bombs door 1 --> Spring Ball Maze
    dw $A72C    ; Aqueduct door 3 --> Botwoon Hallway
    dw $0008
    dw $000A
    dw $AA08    ; Blue Hoppers door 0 --> Metroids 4
    dw $96AE    ; Purple Shaft door 0 --> Bubble Mountain
    dw $93EA    ; Crocomire door 1 --> Crocomire Speedway
    dw $9762    ; Acid Snakes Tunnel door 2 --> Red Pirates Shaft
    dw $A330    ; Glass Tunnel door 0 --> Main Street
    dw $A3F0    ; Fish Tank door 2 --> Mount Everest
    dw $A3FC    ; Fish Tank door 3 --> Mount Everest
    dw $A42C    ; Mount Everest door 0 --> Red Fish
    dw $A228    ; Wrecked Ship Main Shaft door 4 --> Attic
    dw $A294    ; Basement door 0 --> Wrecked Ship Main Shaft
    dw $A60C
    dw $A4BC    ; Crab Shaft door 1 --> Pseudo Plasma Spark
    dw $AE00    ; Tourian Escape 2 custom door 0 --> Tourian Escape 1

; List of vanilla down doors
portals_down_vanilla_table:
    dw $93EA    ; Crocomire door 1 --> Crocomire Speedway
    dw $94CE    ; Post Crocomire Jump door 0 --> Post Crocomire Shaft
    dw $947A    ; Post Crocomire Shaft door 0 --> Post Crocomire Farming
    dw $ADC4    ; Climb custom door 0 --> Parlor
    dw $8A96    ; Crab Maze door 0 --> Forgotten Highway Kago
    dw $8A4E    ; Forgotten Highway Elevator door 0 --> Forgotten Highway Elbow
    dw $8AF6    ; Red Brinstar Elevator door 0 --> Crateria Kihunters
    dw $8E3E    ; Spore Spawn Kihunters door 1 --> Spore Spawn
    dw $A678    ; Oasis door 2 --> Aqueduct Tube
    dw $9156    ; Warehouse Zeela door 2 --> Warehouse Kihunters
    dw $99DE    ; Jail Power Bombs door 1 --> Spring Ball Maze
    dw $9A26    ; Wasteland door 1 --> Red Kihunter Shaft
    dw $A72C    ; Aqueduct door 3 --> Botwoon Hallway
    dw $A4BC    ; Crab Shaft door 1 --> Pseudo Plasma Spark
    dw $A6C0    ; East Sand Hole door 0 --> East Aqueduct Quicksand
    dw $A6A8    ; West Sand Hole door 0 --> West Aqueduct Quicksand
    dw $AA08    ; Blue Hoppers door 0 --> Metroids 4
    dw $AE00    ; Tourian Escape 2 custom door 0 --> Tourian Escape 1
    dw $9762    ; Acid Snakes Tunnel door 2 --> Red Pirates Shaft
    dw $96AE    ; Purple Shaft door 0 --> Bubble Mountain
    dw $A3F0    ; Fish Tank door 2 --> Mount Everest
    dw $A3FC    ; Fish Tank door 3 --> Mount Everest
    dw $A330    ; Glass Tunnel door 0 --> Main Street
    dw $A42C    ; Mount Everest door 0 --> Red Fish
    dw $A294    ; Basement door 0 --> Wrecked Ship Main Shaft
    dw $A228    ; Wrecked Ship Main Shaft door 4 --> Attic

; Above table with portals inverted
portals_down_vanilla_inverted_table:
    dw $93D2    ; Crocomire Speedway door 4 --> Crocomire
    dw $949E    ; Post Crocomire Shaft door 3 --> Post Crocomire Jump
    dw $944A    ; Post Crocomire Farming door 2 --> Post Crocomire Shaft
    dw $898E
    dw $8A8A    ; Forgotten Highway Kago door 1 --> Crab Maze
    dw $8ABA    ; Forgotten Highway Elbow door 1 --> Forgotten Highway Elevator
    dw $8A42    ; Crateria Kihunters door 2 --> Red Brinstar Elevator
    dw $8E56    ; Spore Spawn door 1 --> Spore Spawn Kihunters
    dw $A600
    dw $916E    ; Warehouse Kihunters door 0 --> Warehouse Zeela
    dw $99C6    ; Spring Ball Maze door 2 --> Jail Power Bombs
    dw $99EA    ; Red Kihunter Shaft door 0 --> Wasteland
    dw $A768    ; Botwoon Hallway door 0 --> Aqueduct
    dw $A4E0    ; Pseudo Plasma Spark door 1 --> Crab Shaft
    dw $A6FC
    dw $A6E4
    dw $A9FC    ; Metroids 4 door 1 --> Blue Hoppers
    dw $AAEC    ; Tourian Escape 1 door 1 --> Tourian Escape 2
    dw $97FE    ; Red Pirates Shaft door 1 --> Acid Snakes Tunnel
    dw $9576    ; Bubble Mountain door 3 --> Purple Shaft
    dw $A444    ; Mount Everest door 2 --> Fish Tank
    dw $A450    ; Mount Everest door 3 --> Fish Tank
    dw $A39C    ; Main Street door 0 --> Glass Tunnel
    dw $A474    ; Red Fish door 0 --> Mount Everest
    dw $A21C    ; Wrecked Ship Main Shaft door 3 --> Basement
    dw $A1C8    ; Attic door 0 --> Wrecked Ship Main Shaft

