
; ---------------
; Room Names
; (autogenerated)
; ---------------

org !ORG_ROOMNAMES+$8000
print pc, " roomnames start"
RoomNameTextTable:

org !ORG_ROOMNAMES+$91F8
db $28, "Landing Site", $FF
warnpc !ORG_ROOMNAMES+$9212

org !ORG_ROOMNAMES+$92B3
db $28, "Gauntlet Entrance", $FF
warnpc !ORG_ROOMNAMES+$92CD

org !ORG_ROOMNAMES+$92FD
db $28, "Parlor and Alcatraz", $FF
warnpc !ORG_ROOMNAMES+$9317

org !ORG_ROOMNAMES+$93AA
db $28, "Crateria Power Bombs", $FF
warnpc !ORG_ROOMNAMES+$93C4

org !ORG_ROOMNAMES+$93D5
db $28, "Crateria Save Room", $FF
warnpc !ORG_ROOMNAMES+$93EF

org !ORG_ROOMNAMES+$93FE
db $28, "West Ocean", $FF
warnpc !ORG_ROOMNAMES+$9418

org !ORG_ROOMNAMES+$9461
db $28, "Bowling Alley Path", $FF
warnpc !ORG_ROOMNAMES+$947B

org !ORG_ROOMNAMES+$948C
db $28, "Crateria Kihunter Room", $FF
warnpc !ORG_ROOMNAMES+$94A6

org !ORG_ROOMNAMES+$94CC
db $28, "Forgotten Highway Elev", $FF
warnpc !ORG_ROOMNAMES+$94E6

org !ORG_ROOMNAMES+$94FD
db $28, "East Ocean", $FF
warnpc !ORG_ROOMNAMES+$9517

org !ORG_ROOMNAMES+$9552
db $28, "Forgotten Highway Kagos", $FF
warnpc !ORG_ROOMNAMES+$956C

org !ORG_ROOMNAMES+$957D
db $28, "Crab Maze", $FF
warnpc !ORG_ROOMNAMES+$9597

org !ORG_ROOMNAMES+$95A8
db $28, "Forgotten Highway Elbow", $FF
warnpc !ORG_ROOMNAMES+$95C2

org !ORG_ROOMNAMES+$95D4
db $28, "Crateria Tube", $FF
warnpc !ORG_ROOMNAMES+$95EE

org !ORG_ROOMNAMES+$95FF
db $28, "The Moat", $FF
warnpc !ORG_ROOMNAMES+$9619

org !ORG_ROOMNAMES+$962A
db $28, "Red Brinstar Elev Room", $FF
warnpc !ORG_ROOMNAMES+$9644

org !ORG_ROOMNAMES+$965B
db $28, "Gauntlet E-Tank Room", $FF
warnpc !ORG_ROOMNAMES+$9675

org !ORG_ROOMNAMES+$968F
db $28, "Pre-Bowling", $FF
warnpc !ORG_ROOMNAMES+$96A9

org !ORG_ROOMNAMES+$96BA
db $28, "Climb", $FF
warnpc !ORG_ROOMNAMES+$96D4

org !ORG_ROOMNAMES+$975C
db $28, "Pit Room", $FF
warnpc !ORG_ROOMNAMES+$9776

org !ORG_ROOMNAMES+$97B5
db $28, "Elev to Blue Brinstar", $FF
warnpc !ORG_ROOMNAMES+$97CF

org !ORG_ROOMNAMES+$9804
db $28, "Bomb Torizo Room", $FF
warnpc !ORG_ROOMNAMES+$981E

org !ORG_ROOMNAMES+$9879
db $28, "Flyway", $FF
warnpc !ORG_ROOMNAMES+$9893

org !ORG_ROOMNAMES+$98E2
db $28, "Pre-Map Flyway", $FF
warnpc !ORG_ROOMNAMES+$98FC

org !ORG_ROOMNAMES+$990D
db $28, "Terminator Room", $FF
warnpc !ORG_ROOMNAMES+$9927

org !ORG_ROOMNAMES+$9938
db $28, "Green Brin Elev Room", $FF
warnpc !ORG_ROOMNAMES+$9952

org !ORG_ROOMNAMES+$9969
db $28, "Lower Mushrooms", $FF
warnpc !ORG_ROOMNAMES+$9983

org !ORG_ROOMNAMES+$9994
db $28, "Crateria Map Room", $FF
warnpc !ORG_ROOMNAMES+$99AE

org !ORG_ROOMNAMES+$99BD
db $28, "Green Pirates Shaft", $FF
warnpc !ORG_ROOMNAMES+$99D7

org !ORG_ROOMNAMES+$99F9
db $28, "Crateria Super Room", $FF
warnpc !ORG_ROOMNAMES+$9A13

org !ORG_ROOMNAMES+$9A44
db $28, "Final Missile Bombway", $FF
warnpc !ORG_ROOMNAMES+$9A5E

org !ORG_ROOMNAMES+$9A90
db $28, "The Final Missile", $FF
warnpc !ORG_ROOMNAMES+$9AAA

org !ORG_ROOMNAMES+$9AD9
db $28, "Green Brin Main Shaft", $FF
warnpc !ORG_ROOMNAMES+$9AF3

org !ORG_ROOMNAMES+$9B5B
db $28, "Spore Spawn Super Room", $FF
warnpc !ORG_ROOMNAMES+$9B75

org !ORG_ROOMNAMES+$9B9D
db $28, "Brinstar Pre-Map Room", $FF
warnpc !ORG_ROOMNAMES+$9BB7

org !ORG_ROOMNAMES+$9BC8
db $28, "Early Supers Room", $FF
warnpc !ORG_ROOMNAMES+$9BE2

org !ORG_ROOMNAMES+$9C07
db $28, "Brinstar Reserve Tank", $FF
warnpc !ORG_ROOMNAMES+$9C21

org !ORG_ROOMNAMES+$9C35
db $28, "Brinstar Map Room", $FF
warnpc !ORG_ROOMNAMES+$9C4F

org !ORG_ROOMNAMES+$9C5E
db $28, "Green Brin Firefleas", $FF
warnpc !ORG_ROOMNAMES+$9C78

org !ORG_ROOMNAMES+$9C89
db $28, "Green Brin Missile Refi", $FF
warnpc !ORG_ROOMNAMES+$9CA3

org !ORG_ROOMNAMES+$9CB3
db $28, "Dachora Room", $FF
warnpc !ORG_ROOMNAMES+$9CCD

org !ORG_ROOMNAMES+$9D19
db $28, "Big Pink", $FF
warnpc !ORG_ROOMNAMES+$9D33

org !ORG_ROOMNAMES+$9D9C
db $28, "Spore Spawn Kihunters", $FF
warnpc !ORG_ROOMNAMES+$9DB6

org !ORG_ROOMNAMES+$9DC7
db $28, "Spore Spawn Room", $FF
warnpc !ORG_ROOMNAMES+$9DE1

org !ORG_ROOMNAMES+$9E11
db $28, "Pink Brin Power Bombs", $FF
warnpc !ORG_ROOMNAMES+$9E2B

org !ORG_ROOMNAMES+$9E52
db $28, "Green Hill Zone", $FF
warnpc !ORG_ROOMNAMES+$9E6C

org !ORG_ROOMNAMES+$9E9F
db $28, "Morph Ball Room", $FF
warnpc !ORG_ROOMNAMES+$9EB9

org !ORG_ROOMNAMES+$9F11
db $28, "Construction Zone", $FF
warnpc !ORG_ROOMNAMES+$9F2B

org !ORG_ROOMNAMES+$9F64
db $28, "Blue Brinstar E-Tank", $FF
warnpc !ORG_ROOMNAMES+$9F7E

org !ORG_ROOMNAMES+$9FBA
db $28, "Noob Bridge", $FF
warnpc !ORG_ROOMNAMES+$9FD4

org !ORG_ROOMNAMES+$9FE5
db $28, "Green Brinstar Beetoms", $FF
warnpc !ORG_ROOMNAMES+$9FFF

org !ORG_ROOMNAMES+$A011
db $28, "Etecoon E-Tank Room", $FF
warnpc !ORG_ROOMNAMES+$A02B

org !ORG_ROOMNAMES+$A051
db $28, "Etecoon Super Room", $FF
warnpc !ORG_ROOMNAMES+$A06B

org !ORG_ROOMNAMES+$A07B
db $28, "Dachora Energy Refill", $FF
warnpc !ORG_ROOMNAMES+$A095

org !ORG_ROOMNAMES+$A0A4
db $28, "Spore Spawn Farming", $FF
warnpc !ORG_ROOMNAMES+$A0BE

org !ORG_ROOMNAMES+$A0D2
db $28, "Waterway E-Tank Room", $FF
warnpc !ORG_ROOMNAMES+$A0EC

org !ORG_ROOMNAMES+$A107
db $28, "First Missile Room", $FF
warnpc !ORG_ROOMNAMES+$A121

org !ORG_ROOMNAMES+$A130
db $28, "Pink Brinstar Hoppers", $FF
warnpc !ORG_ROOMNAMES+$A14A

org !ORG_ROOMNAMES+$A15B
db $28, "Hopper Energy Tank Room", $FF
warnpc !ORG_ROOMNAMES+$A175

org !ORG_ROOMNAMES+$A184
db $28, "Big Pink Save Room", $FF
warnpc !ORG_ROOMNAMES+$A19E

org !ORG_ROOMNAMES+$A1AD
db $28, "Blue Brinstar Boulders", $FF
warnpc !ORG_ROOMNAMES+$A1C7

org !ORG_ROOMNAMES+$A1D8
db $28, "Billy Mays Room", $FF
warnpc !ORG_ROOMNAMES+$A1F2

org !ORG_ROOMNAMES+$A201
db $28, "Green Brin Save Room", $FF
warnpc !ORG_ROOMNAMES+$A21B

org !ORG_ROOMNAMES+$A22A
db $28, "Etecoon Save Room", $FF
warnpc !ORG_ROOMNAMES+$A244

org !ORG_ROOMNAMES+$A253
db $28, "Red Tower", $FF
warnpc !ORG_ROOMNAMES+$A26D

org !ORG_ROOMNAMES+$A293
db $28, "Red Brinstar Firefleas", $FF
warnpc !ORG_ROOMNAMES+$A2AD

org !ORG_ROOMNAMES+$A2CE
db $28, "X-Ray Scope Room", $FF
warnpc !ORG_ROOMNAMES+$A2E8

org !ORG_ROOMNAMES+$A2F7
db $28, "Hellway", $FF
warnpc !ORG_ROOMNAMES+$A311

org !ORG_ROOMNAMES+$A322
db $28, "Caterpillar Room", $FF
warnpc !ORG_ROOMNAMES+$A33C

org !ORG_ROOMNAMES+$A37C
db $28, "Beta Power Bomb Room", $FF
warnpc !ORG_ROOMNAMES+$A396

org !ORG_ROOMNAMES+$A3AE
db $28, "Alpha Power Bomb Room", $FF
warnpc !ORG_ROOMNAMES+$A3C8

org !ORG_ROOMNAMES+$A3DD
db $28, "Bat Room", $FF
warnpc !ORG_ROOMNAMES+$A3F7

org !ORG_ROOMNAMES+$A408
db $28, "Below Spazer", $FF
warnpc !ORG_ROOMNAMES+$A422

org !ORG_ROOMNAMES+$A447
db $28, "Spazer Room", $FF
warnpc !ORG_ROOMNAMES+$A461

org !ORG_ROOMNAMES+$A471
db $28, "Warehouse Zeela Room", $FF
warnpc !ORG_ROOMNAMES+$A48B

org !ORG_ROOMNAMES+$A4B1
db $28, "Warehouse E-Tank Room", $FF
warnpc !ORG_ROOMNAMES+$A4CB

org !ORG_ROOMNAMES+$A4DA
db $28, "Warehouse Kihunter Room", $FF
warnpc !ORG_ROOMNAMES+$A4F4

org !ORG_ROOMNAMES+$A521
db $28, "Baby Kraid Room", $FF
warnpc !ORG_ROOMNAMES+$A53B

org !ORG_ROOMNAMES+$A56B
db $28, "Kraid Eye Door Room", $FF
warnpc !ORG_ROOMNAMES+$A585

org !ORG_ROOMNAMES+$A59F
db $28, "Kraid Room", $FF
warnpc !ORG_ROOMNAMES+$A5B9

org !ORG_ROOMNAMES+$A5ED
db $28, "Statues Hallway", $FF
warnpc !ORG_ROOMNAMES+$A607

org !ORG_ROOMNAMES+$A618
db $28, "Sloaters Refill", $FF
warnpc !ORG_ROOMNAMES+$A632

org !ORG_ROOMNAMES+$A641
db $28, "Kraid Refill Stations", $FF
warnpc !ORG_ROOMNAMES+$A65B

org !ORG_ROOMNAMES+$A66A
db $28, "Statues Room", $FF
warnpc !ORG_ROOMNAMES+$A684

org !ORG_ROOMNAMES+$A6A1
db $28, "Warehouse Entrance", $FF
warnpc !ORG_ROOMNAMES+$A6BB

org !ORG_ROOMNAMES+$A6E2
db $28, "Varia Suit Room", $FF
warnpc !ORG_ROOMNAMES+$A6FC

org !ORG_ROOMNAMES+$A70B
db $28, "Warehouse Save Room", $FF
warnpc !ORG_ROOMNAMES+$A725

org !ORG_ROOMNAMES+$A734
db $28, "Red Brinstar Save Room", $FF
warnpc !ORG_ROOMNAMES+$A74E

org !ORG_ROOMNAMES+$A75D
db $28, "Ice Beam Acid Room", $FF
warnpc !ORG_ROOMNAMES+$A777

org !ORG_ROOMNAMES+$A788
db $28, "Cathedral", $FF
warnpc !ORG_ROOMNAMES+$A7A2

org !ORG_ROOMNAMES+$A7B3
db $28, "Cathedral Entrance", $FF
warnpc !ORG_ROOMNAMES+$A7CD

org !ORG_ROOMNAMES+$A7DE
db $28, "Business Center", $FF
warnpc !ORG_ROOMNAMES+$A7F8

org !ORG_ROOMNAMES+$A815
db $28, "Ice Beam Gate Room", $FF
warnpc !ORG_ROOMNAMES+$A82F

org !ORG_ROOMNAMES+$A865
db $28, "Ice Beam Tutorial Room", $FF
warnpc !ORG_ROOMNAMES+$A87F

org !ORG_ROOMNAMES+$A890
db $28, "Ice Beam Room", $FF
warnpc !ORG_ROOMNAMES+$A8AA

org !ORG_ROOMNAMES+$A8B9
db $28, "Ice Beam Snake Room", $FF
warnpc !ORG_ROOMNAMES+$A8D3

org !ORG_ROOMNAMES+$A8F8
db $28, "Crumble Shaft", $FF
warnpc !ORG_ROOMNAMES+$A912

org !ORG_ROOMNAMES+$A923
db $28, "Crocomire Speedway", $FF
warnpc !ORG_ROOMNAMES+$A93D

org !ORG_ROOMNAMES+$A98D
db $28, "Crocomire's Room", $FF
warnpc !ORG_ROOMNAMES+$A9A7

org !ORG_ROOMNAMES+$A9E5
db $28, "Hi Jump Boots Room", $FF
warnpc !ORG_ROOMNAMES+$A9FF

org !ORG_ROOMNAMES+$AA0E
db $28, "Crocomire Escape", $FF
warnpc !ORG_ROOMNAMES+$AA28

org !ORG_ROOMNAMES+$AA41
db $28, "Hi Jump E-Tank Room", $FF
warnpc !ORG_ROOMNAMES+$AA5B

org !ORG_ROOMNAMES+$AA82
db $28, "Post Croc Farming Room", $FF
warnpc !ORG_ROOMNAMES+$AA9C

org !ORG_ROOMNAMES+$AAB5
db $28, "Post Croc Save Room", $FF
warnpc !ORG_ROOMNAMES+$AACF

org !ORG_ROOMNAMES+$AADE
db $28, "Post Croc Power Bombs", $FF
warnpc !ORG_ROOMNAMES+$AAF8

org !ORG_ROOMNAMES+$AB07
db $28, "Post Crocomire Shaft", $FF
warnpc !ORG_ROOMNAMES+$AB21

org !ORG_ROOMNAMES+$AB3B
db $28, "Post Croc Missile Room", $FF
warnpc !ORG_ROOMNAMES+$AB55

org !ORG_ROOMNAMES+$AB64
db $28, "Grapple Tutorial Room 3", $FF
warnpc !ORG_ROOMNAMES+$AB7E

org !ORG_ROOMNAMES+$AB8F
db $28, "Post Croc Jump Room", $FF
warnpc !ORG_ROOMNAMES+$ABA9

org !ORG_ROOMNAMES+$ABD2
db $28, "Grapple Tutorial Room 2", $FF
warnpc !ORG_ROOMNAMES+$ABEC

org !ORG_ROOMNAMES+$AC00
db $28, "Grapple Tutorial Room 1", $FF
warnpc !ORG_ROOMNAMES+$AC1A

org !ORG_ROOMNAMES+$AC2B
db $28, "Grapple Beam Room", $FF
warnpc !ORG_ROOMNAMES+$AC45

org !ORG_ROOMNAMES+$AC5A
db $28, "Norfair Reserve Tank", $FF
warnpc !ORG_ROOMNAMES+$AC74

org !ORG_ROOMNAMES+$AC83
db $28, "Green Bubbles Missiles", $FF
warnpc !ORG_ROOMNAMES+$AC9D

org !ORG_ROOMNAMES+$ACB3
db $28, "Bubble Mountain", $FF
warnpc !ORG_ROOMNAMES+$ACCD

org !ORG_ROOMNAMES+$ACF0
db $28, "Speed Booster Hall", $FF
warnpc !ORG_ROOMNAMES+$AD0A

org !ORG_ROOMNAMES+$AD1B
db $28, "Speed Booster Room", $FF
warnpc !ORG_ROOMNAMES+$AD35

org !ORG_ROOMNAMES+$AD5E
db $28, "Single Chamber", $FF
warnpc !ORG_ROOMNAMES+$AD78

org !ORG_ROOMNAMES+$ADAD
db $28, "Double Chamber", $FF
warnpc !ORG_ROOMNAMES+$ADC7

org !ORG_ROOMNAMES+$ADDE
db $28, "Wave Beam Room", $FF
warnpc !ORG_ROOMNAMES+$ADF8

org !ORG_ROOMNAMES+$AE07
db $28, "Spiky Platforms Tunnel", $FF
warnpc !ORG_ROOMNAMES+$AE21

org !ORG_ROOMNAMES+$AE32
db $28, "Volcano Room", $FF
warnpc !ORG_ROOMNAMES+$AE4C

org !ORG_ROOMNAMES+$AE74
db $28, "Kronic Boost Room", $FF
warnpc !ORG_ROOMNAMES+$AE8E

org !ORG_ROOMNAMES+$AEB4
db $28, "Magdollite Tunnel", $FF
warnpc !ORG_ROOMNAMES+$AECE

org !ORG_ROOMNAMES+$AEDF
db $28, "Purple Shaft", $FF
warnpc !ORG_ROOMNAMES+$AEF9

org !ORG_ROOMNAMES+$AF14
db $28, "Lava Dive Room", $FF
warnpc !ORG_ROOMNAMES+$AF2E

org !ORG_ROOMNAMES+$AF3F
db $28, "Lower Norfair Elevator", $FF
warnpc !ORG_ROOMNAMES+$AF59

org !ORG_ROOMNAMES+$AF72
db $28, "Upper Norf Farming Room", $FF
warnpc !ORG_ROOMNAMES+$AF8C

org !ORG_ROOMNAMES+$AFA3
db $28, "Rising Tide", $FF
warnpc !ORG_ROOMNAMES+$AFBD

org !ORG_ROOMNAMES+$AFCE
db $28, "Acid Snakes Tunnel", $FF
warnpc !ORG_ROOMNAMES+$AFE8

org !ORG_ROOMNAMES+$AFFB
db $28, "Spiky Acid Snakes Tunnel", $FF
warnpc !ORG_ROOMNAMES+$B015

org !ORG_ROOMNAMES+$B026
db $28, "Nutella Refill", $FF
warnpc !ORG_ROOMNAMES+$B040

org !ORG_ROOMNAMES+$B051
db $28, "Purple Farming Room", $FF
warnpc !ORG_ROOMNAMES+$B06B

org !ORG_ROOMNAMES+$B07A
db $28, "Bat Cave", $FF
warnpc !ORG_ROOMNAMES+$B094

org !ORG_ROOMNAMES+$B0B4
db $28, "Norfair Map Room", $FF
warnpc !ORG_ROOMNAMES+$B0CE

org !ORG_ROOMNAMES+$B0DD
db $28, "Bubble Mountain Save", $FF
warnpc !ORG_ROOMNAMES+$B0F7

org !ORG_ROOMNAMES+$B106
db $28, "Frog Speedway", $FF
warnpc !ORG_ROOMNAMES+$B120

org !ORG_ROOMNAMES+$B139
db $28, "Red Pirate Shaft", $FF
warnpc !ORG_ROOMNAMES+$B153

org !ORG_ROOMNAMES+$B167
db $28, "Frog Savestation", $FF
warnpc !ORG_ROOMNAMES+$B181

org !ORG_ROOMNAMES+$B192
db $28, "Crocomire Save Room", $FF
warnpc !ORG_ROOMNAMES+$B1AC

org !ORG_ROOMNAMES+$B1BB
db $28, "LN Elevator Save Room", $FF
warnpc !ORG_ROOMNAMES+$B1D5

org !ORG_ROOMNAMES+$B1E5
db $28, "Acid Statue Room", $FF
warnpc !ORG_ROOMNAMES+$B1FF

org !ORG_ROOMNAMES+$B236
db $28, "Main Hall", $FF
warnpc !ORG_ROOMNAMES+$B250

org !ORG_ROOMNAMES+$B283
db $28, "Golden Torizo's Room", $FF
warnpc !ORG_ROOMNAMES+$B29D

org !ORG_ROOMNAMES+$B2DA
db $28, "Fast Ripper Room", $FF
warnpc !ORG_ROOMNAMES+$B2F4

org !ORG_ROOMNAMES+$B305
db $28, "GT Energy Recharge", $FF
warnpc !ORG_ROOMNAMES+$B31F

org !ORG_ROOMNAMES+$B32E
db $28, "Ridley's Room", $FF
warnpc !ORG_ROOMNAMES+$B348

org !ORG_ROOMNAMES+$B37A
db $28, "LN Farming Room", $FF
warnpc !ORG_ROOMNAMES+$B394

org !ORG_ROOMNAMES+$B3A5
db $28, "Fast Pillars Setup Room", $FF
warnpc !ORG_ROOMNAMES+$B3BF

org !ORG_ROOMNAMES+$B40A
db $28, "Mickey Mouse Room", $FF
warnpc !ORG_ROOMNAMES+$B424

org !ORG_ROOMNAMES+$B457
db $28, "Pillar Room", $FF
warnpc !ORG_ROOMNAMES+$B471

org !ORG_ROOMNAMES+$B482
db $28, "Plowerhouse Room", $FF
warnpc !ORG_ROOMNAMES+$B49C

org !ORG_ROOMNAMES+$B4AD
db $28, "Worst Room In The Game", $FF
warnpc !ORG_ROOMNAMES+$B4C7

org !ORG_ROOMNAMES+$B4E5
db $28, "Amphitheatre", $FF
warnpc !ORG_ROOMNAMES+$B4FF

org !ORG_ROOMNAMES+$B510
db $28, "LN Spring Ball Maze", $FF
warnpc !ORG_ROOMNAMES+$B52A

org !ORG_ROOMNAMES+$B55A
db $28, "LN Escape Power Bombs", $FF
warnpc !ORG_ROOMNAMES+$B574

org !ORG_ROOMNAMES+$B585
db $28, "Red Kihunter Shaft", $FF
warnpc !ORG_ROOMNAMES+$B59F

org !ORG_ROOMNAMES+$B5D5
db $28, "Wasteland", $FF
warnpc !ORG_ROOMNAMES+$B5EF

org !ORG_ROOMNAMES+$B62B
db $28, "Metal Pirates Room", $FF
warnpc !ORG_ROOMNAMES+$B645

org !ORG_ROOMNAMES+$B656
db $28, "Three Musketeers' Room", $FF
warnpc !ORG_ROOMNAMES+$B670

org !ORG_ROOMNAMES+$B698
db $28, "Ridley Tank Room", $FF
warnpc !ORG_ROOMNAMES+$B6B2

org !ORG_ROOMNAMES+$B6C1
db $28, "Screw Attack Room", $FF
warnpc !ORG_ROOMNAMES+$B6DB

org !ORG_ROOMNAMES+$B6EE
db $28, "LN Fireflea Room", $FF
warnpc !ORG_ROOMNAMES+$B708

org !ORG_ROOMNAMES+$B741
db $28, "Lower Norfair Save Room", $FF
warnpc !ORG_ROOMNAMES+$B75B

org !ORG_ROOMNAMES+$C98E
db $28, "Bowling Alley", $FF
warnpc !ORG_ROOMNAMES+$C9A8

org !ORG_ROOMNAMES+$CA08
db $28, "Wrecked Ship Entrance", $FF
warnpc !ORG_ROOMNAMES+$CA22

org !ORG_ROOMNAMES+$CA52
db $28, "Attic", $FF
warnpc !ORG_ROOMNAMES+$CA6C

org !ORG_ROOMNAMES+$CAAE
db $28, "Assembly Line", $FF
warnpc !ORG_ROOMNAMES+$CAC8

org !ORG_ROOMNAMES+$CAF6
db $28, "Wrecked Ship Main Shaft", $FF
warnpc !ORG_ROOMNAMES+$CB10

org !ORG_ROOMNAMES+$CB8B
db $28, "Spiky Death Room", $FF
warnpc !ORG_ROOMNAMES+$CBA5

org !ORG_ROOMNAMES+$CBD5
db $28, "Electric Death Room", $FF
warnpc !ORG_ROOMNAMES+$CBEF

org !ORG_ROOMNAMES+$CC27
db $28, "Wrecked Ship E-Tank", $FF
warnpc !ORG_ROOMNAMES+$CC41

org !ORG_ROOMNAMES+$CC6F
db $28, "Basement", $FF
warnpc !ORG_ROOMNAMES+$CC89

org !ORG_ROOMNAMES+$CCCB
db $28, "Wrecked Ship Map Room", $FF
warnpc !ORG_ROOMNAMES+$CCE5

org !ORG_ROOMNAMES+$CD13
db $28, "Phantoon's Room", $FF
warnpc !ORG_ROOMNAMES+$CD2D

org !ORG_ROOMNAMES+$CD5C
db $28, "Sponge Bath", $FF
warnpc !ORG_ROOMNAMES+$CD76

org !ORG_ROOMNAMES+$CDA8
db $28, "WS West Super Room", $FF
warnpc !ORG_ROOMNAMES+$CDC2

org !ORG_ROOMNAMES+$CDF1
db $28, "WS East Super Room", $FF
warnpc !ORG_ROOMNAMES+$CE0B

org !ORG_ROOMNAMES+$CE40
db $28, "Gravity Suit Room", $FF
warnpc !ORG_ROOMNAMES+$CE5A

org !ORG_ROOMNAMES+$CE8A
db $28, "Wrecked Ship Save Room", $FF
warnpc !ORG_ROOMNAMES+$CEA4

org !ORG_ROOMNAMES+$CED2
db $28, "Glass Tunnel Save Room", $FF
warnpc !ORG_ROOMNAMES+$CEEC

org !ORG_ROOMNAMES+$CEFB
db $28, "Glass Tunnel", $FF
warnpc !ORG_ROOMNAMES+$CF15

org !ORG_ROOMNAMES+$CF54
db $28, "West Tunnel", $FF
warnpc !ORG_ROOMNAMES+$CF6E

org !ORG_ROOMNAMES+$CF80
db $28, "East Tunnel", $FF
warnpc !ORG_ROOMNAMES+$CF9A

org !ORG_ROOMNAMES+$CFC9
db $28, "Main Street", $FF
warnpc !ORG_ROOMNAMES+$CFE3

org !ORG_ROOMNAMES+$D017
db $28, "Fish Tank", $FF
warnpc !ORG_ROOMNAMES+$D031

org !ORG_ROOMNAMES+$D055
db $28, "Mama Turtle Room", $FF
warnpc !ORG_ROOMNAMES+$D06F

org !ORG_ROOMNAMES+$D08A
db $28, "Crab Tunnel", $FF
warnpc !ORG_ROOMNAMES+$D0A4

org !ORG_ROOMNAMES+$D0B9
db $28, "Mt. Everest", $FF
warnpc !ORG_ROOMNAMES+$D0D3

org !ORG_ROOMNAMES+$D104
db $28, "Red Fish Room", $FF
warnpc !ORG_ROOMNAMES+$D11E

org !ORG_ROOMNAMES+$D13B
db $28, "Watering Hole", $FF
warnpc !ORG_ROOMNAMES+$D155

org !ORG_ROOMNAMES+$D16D
db $28, "N.West Maridia Bug Room", $FF
warnpc !ORG_ROOMNAMES+$D187

org !ORG_ROOMNAMES+$D1A3
db $28, "Crab Shaft", $FF
warnpc !ORG_ROOMNAMES+$D1BD

org !ORG_ROOMNAMES+$D1DD
db $28, "Pseudo Plasma Spark", $FF
warnpc !ORG_ROOMNAMES+$D1F7

org !ORG_ROOMNAMES+$D21C
db $28, "Crab Hole", $FF
warnpc !ORG_ROOMNAMES+$D236

org !ORG_ROOMNAMES+$D252
db $28, "West Sand Hall Tunnel", $FF
warnpc !ORG_ROOMNAMES+$D26C

org !ORG_ROOMNAMES+$D27E
db $28, "Plasma Tutorial Room", $FF
warnpc !ORG_ROOMNAMES+$D298

org !ORG_ROOMNAMES+$D2AA
db $28, "Plasma Room", $FF
warnpc !ORG_ROOMNAMES+$D2C4

org !ORG_ROOMNAMES+$D2D9
db $28, "Thread The Needle Room", $FF
warnpc !ORG_ROOMNAMES+$D2F3

org !ORG_ROOMNAMES+$D30B
db $28, "Maridia Elevator Room", $FF
warnpc !ORG_ROOMNAMES+$D325

org !ORG_ROOMNAMES+$D340
db $28, "Plasma Spark Room", $FF
warnpc !ORG_ROOMNAMES+$D35A

org !ORG_ROOMNAMES+$D387
db $28, "Kassiuz Room", $FF
warnpc !ORG_ROOMNAMES+$D3A1

org !ORG_ROOMNAMES+$D3B6
db $28, "Maridia Map Room", $FF
warnpc !ORG_ROOMNAMES+$D3D0

org !ORG_ROOMNAMES+$D3DF
db $28, "Forgotten Highway Save", $FF
warnpc !ORG_ROOMNAMES+$D3F9

org !ORG_ROOMNAMES+$D408
db $28, "Toilet", $FF
warnpc !ORG_ROOMNAMES+$D422

org !ORG_ROOMNAMES+$D433
db $28, "Bug Sand Hole", $FF
warnpc !ORG_ROOMNAMES+$D44D

org !ORG_ROOMNAMES+$D461
db $28, "West Sand Hall", $FF
warnpc !ORG_ROOMNAMES+$D47B

org !ORG_ROOMNAMES+$D48E
db $28, "Oasis", $FF
warnpc !ORG_ROOMNAMES+$D4A8

org !ORG_ROOMNAMES+$D4C2
db $28, "East Sand Hall", $FF
warnpc !ORG_ROOMNAMES+$D4DC

org !ORG_ROOMNAMES+$D4EF
db $28, "West Sand Hole", $FF
warnpc !ORG_ROOMNAMES+$D509

org !ORG_ROOMNAMES+$D51E
db $28, "East Sand Hole", $FF
warnpc !ORG_ROOMNAMES+$D538

org !ORG_ROOMNAMES+$D54D
db $28, "West Aqueduct Quicksand", $FF
warnpc !ORG_ROOMNAMES+$D567

org !ORG_ROOMNAMES+$D57A
db $28, "East Aqueduct Quicksand", $FF
warnpc !ORG_ROOMNAMES+$D594

org !ORG_ROOMNAMES+$D5A7
db $28, "Aqueduct", $FF
warnpc !ORG_ROOMNAMES+$D5C1

org !ORG_ROOMNAMES+$D5EC
db $28, "Butterfly Room", $FF
warnpc !ORG_ROOMNAMES+$D606

org !ORG_ROOMNAMES+$D617
db $28, "Botwoon Hallway", $FF
warnpc !ORG_ROOMNAMES+$D631

org !ORG_ROOMNAMES+$D646
db $28, "Pants Room", $FF
warnpc !ORG_ROOMNAMES+$D660

org !ORG_ROOMNAMES+$D69A
db $28, "East Pants Room", $FF
warnpc !ORG_ROOMNAMES+$D6B4

org !ORG_ROOMNAMES+$D6D0
db $28, "Spring Ball Room", $FF
warnpc !ORG_ROOMNAMES+$D6EA

org !ORG_ROOMNAMES+$D6FD
db $28, "Below Botwoon E-Tank", $FF
warnpc !ORG_ROOMNAMES+$D717

org !ORG_ROOMNAMES+$D72A
db $28, "Colosseum", $FF
warnpc !ORG_ROOMNAMES+$D744

org !ORG_ROOMNAMES+$D765
db $28, "Aqueduct Save Room", $FF
warnpc !ORG_ROOMNAMES+$D77F

org !ORG_ROOMNAMES+$D78F
db $28, "The Precious Room", $FF
warnpc !ORG_ROOMNAMES+$D7A9

org !ORG_ROOMNAMES+$D7E4
db $28, "Botwoon E-Tank Room", $FF
warnpc !ORG_ROOMNAMES+$D7FE

org !ORG_ROOMNAMES+$D81A
db $28, "Draygon Save Room", $FF
warnpc !ORG_ROOMNAMES+$D834

org !ORG_ROOMNAMES+$D845
db $28, "Maridia Missile Refill", $FF
warnpc !ORG_ROOMNAMES+$D85F

org !ORG_ROOMNAMES+$D86E
db $28, "Plasma Beach Quicksand", $FF
warnpc !ORG_ROOMNAMES+$D888

org !ORG_ROOMNAMES+$D898
db $28, "Botwoon Quicksand Room", $FF
warnpc !ORG_ROOMNAMES+$D8B2

org !ORG_ROOMNAMES+$D8C5
db $28, "Shaktool Room", $FF
warnpc !ORG_ROOMNAMES+$D8DF

org !ORG_ROOMNAMES+$D913
db $28, "Halfie Climb Room", $FF
warnpc !ORG_ROOMNAMES+$D92D

org !ORG_ROOMNAMES+$D95E
db $28, "Botwoon's Room", $FF
warnpc !ORG_ROOMNAMES+$D978

org !ORG_ROOMNAMES+$D9AA
db $28, "Space Jump Room", $FF
warnpc !ORG_ROOMNAMES+$D9C4

org !ORG_ROOMNAMES+$D9D4
db $28, "Maridia Energy Refill", $FF
warnpc !ORG_ROOMNAMES+$D9EE

org !ORG_ROOMNAMES+$D9FE
db $28, "West Cactus Alley Room", $FF
warnpc !ORG_ROOMNAMES+$DA18

org !ORG_ROOMNAMES+$DA2B
db $28, "East Cactus Alley Room", $FF
warnpc !ORG_ROOMNAMES+$DA45

org !ORG_ROOMNAMES+$DA60
db $28, "Draygon's Room", $FF
warnpc !ORG_ROOMNAMES+$DA7A

org !ORG_ROOMNAMES+$DAAE
db $28, "Tourian First Room", $FF
warnpc !ORG_ROOMNAMES+$DAC8

org !ORG_ROOMNAMES+$DAE1
db $28, "Metroid Room 1", $FF
warnpc !ORG_ROOMNAMES+$DAFB

org !ORG_ROOMNAMES+$DB31
db $28, "Metroid Room 2", $FF
warnpc !ORG_ROOMNAMES+$DB4B

org !ORG_ROOMNAMES+$DB7D
db $28, "Metroid Room 3", $FF
warnpc !ORG_ROOMNAMES+$DB97

org !ORG_ROOMNAMES+$DBCD
db $28, "Metroid Room 4", $FF
warnpc !ORG_ROOMNAMES+$DBE7

org !ORG_ROOMNAMES+$DC19
db $28, "Blue Hopper Room", $FF
warnpc !ORG_ROOMNAMES+$DC33

org !ORG_ROOMNAMES+$DC65
db $28, "Dust Torizo Room", $FF
warnpc !ORG_ROOMNAMES+$DC7F

org !ORG_ROOMNAMES+$DCB1
db $28, "Big Boy Room", $FF
warnpc !ORG_ROOMNAMES+$DCCB

org !ORG_ROOMNAMES+$DCFF
db $28, "Seaweed Room", $FF
warnpc !ORG_ROOMNAMES+$DD19

org !ORG_ROOMNAMES+$DD2E
db $28, "Tourian Recharge Room", $FF
warnpc !ORG_ROOMNAMES+$DD48

org !ORG_ROOMNAMES+$DD58
db $28, "Mother Brain Room", $FF
warnpc !ORG_ROOMNAMES+$DD72

org !ORG_ROOMNAMES+$DDC4
db $28, "Tourian Eye Door Room", $FF
warnpc !ORG_ROOMNAMES+$DDDE

org !ORG_ROOMNAMES+$DDF3
db $28, "Rinka Shaft", $FF
warnpc !ORG_ROOMNAMES+$DE0D

org !ORG_ROOMNAMES+$DE23
db $28, "Mother Brain Save Room", $FF
warnpc !ORG_ROOMNAMES+$DE3D

org !ORG_ROOMNAMES+$DE4D
db $28, "Tourian Escape Room 1", $FF
warnpc !ORG_ROOMNAMES+$DE67

org !ORG_ROOMNAMES+$DE7A
db $28, "Tourian Escape Room 2", $FF
warnpc !ORG_ROOMNAMES+$DE94

org !ORG_ROOMNAMES+$DEA7
db $28, "Tourian Escape Room 3", $FF
warnpc !ORG_ROOMNAMES+$DEC1

org !ORG_ROOMNAMES+$DEDE
db $28, "Tourian Escape Room 4", $FF
warnpc !ORG_ROOMNAMES+$DEF8

org !ORG_ROOMNAMES+$DF1B
db $28, "Upper Tourian Save Room", $FF
warnpc !ORG_ROOMNAMES+$DF35

org !ORG_ROOMNAMES+$DF45
db $28, "Ceres Elevator Room", $FF
warnpc !ORG_ROOMNAMES+$DF5F

org !ORG_ROOMNAMES+$DF8D
db $28, "Falling Tile Room", $FF
warnpc !ORG_ROOMNAMES+$DFA7

org !ORG_ROOMNAMES+$DFD7
db $28, "Magnet Stairs Room", $FF
warnpc !ORG_ROOMNAMES+$DFF1

org !ORG_ROOMNAMES+$E021
db $28, "Dead Scientist Room", $FF
warnpc !ORG_ROOMNAMES+$E03B

org !ORG_ROOMNAMES+$E06B
db $28, "58 Escape", $FF
warnpc !ORG_ROOMNAMES+$E085

org !ORG_ROOMNAMES+$E0B5
db $28, "Ceres Ridley's Room", $FF
warnpc !ORG_ROOMNAMES+$E0CF

org !ORG_ROOMNAMES+$E82C
db $28, "Debug Room", $FF
warnpc !ORG_ROOMNAMES+$E844

print pc, " roomnames end"

