
; ---------------
; Room Names
; (autogenerated)
; ---------------

if !FEATURE_ROOM_NAMES
org !ORG_ROOMNAMES+$8000
print pc, " roomnames start"
RoomNameTextTable:
endif
ROOM:

org !ORG_ROOMNAMES+$91F8
  .LandingSite
if !FEATURE_ROOM_NAMES
    db $28, "Landing Site", $FF
endif

org !ORG_ROOMNAMES+$92B3
  .GauntletEntrance
if !FEATURE_ROOM_NAMES
    db $28, "Gauntlet Entrance", $FF
endif

org !ORG_ROOMNAMES+$92FD
  .ParlorAndAlcatraz
if !FEATURE_ROOM_NAMES
    db $28, "Parlor and Alcatraz", $FF
endif

org !ORG_ROOMNAMES+$93AA
  .CrateriaPowerBombs
if !FEATURE_ROOM_NAMES
    db $28, "Crateria Power Bombs", $FF
endif

org !ORG_ROOMNAMES+$93D5
  .CrateriaSaveRoom
if !FEATURE_ROOM_NAMES
    db $28, "Crateria Save Room", $FF
endif

org !ORG_ROOMNAMES+$93FE
  .WestOcean
if !FEATURE_ROOM_NAMES
    db $28, "West Ocean", $FF
endif

org !ORG_ROOMNAMES+$9461
  .BowlingAlleyPath
if !FEATURE_ROOM_NAMES
    db $28, "Bowling Alley Path", $FF
endif

org !ORG_ROOMNAMES+$948C
  .CrateriaKihunterRoom
if !FEATURE_ROOM_NAMES
    db $28, "Crateria Kihunter Room", $FF
endif

org !ORG_ROOMNAMES+$94CC
  .ForgottenHighwayElev
if !FEATURE_ROOM_NAMES
    db $28, "Forgotten Highway Elev", $FF
endif

org !ORG_ROOMNAMES+$94FD
  .EastOcean
if !FEATURE_ROOM_NAMES
    db $28, "East Ocean", $FF
endif

org !ORG_ROOMNAMES+$9552
  .ForgottenHighwayKagos
if !FEATURE_ROOM_NAMES
    db $28, "Forgotten Highway Kagos", $FF
endif

org !ORG_ROOMNAMES+$957D
  .CrabMaze
if !FEATURE_ROOM_NAMES
    db $28, "Crab Maze", $FF
endif

org !ORG_ROOMNAMES+$95A8
  .ForgottenHighwayElbow
if !FEATURE_ROOM_NAMES
    db $28, "Forgotten Highway Elbow", $FF
endif

org !ORG_ROOMNAMES+$95D4
  .CrateriaTube
if !FEATURE_ROOM_NAMES
    db $28, "Crateria Tube", $FF
endif

org !ORG_ROOMNAMES+$95FF
  .TheMoat
if !FEATURE_ROOM_NAMES
    db $28, "The Moat", $FF
endif

org !ORG_ROOMNAMES+$962A
  .RedBrinstarElevRoom
if !FEATURE_ROOM_NAMES
    db $28, "Red Brinstar Elev Room", $FF
endif

org !ORG_ROOMNAMES+$965B
  .GauntletETankRoom
if !FEATURE_ROOM_NAMES
    db $28, "Gauntlet E-Tank Room", $FF
endif

org !ORG_ROOMNAMES+$968F
  .PreBowling
if !FEATURE_ROOM_NAMES
    db $28, "Pre-Bowling", $FF
endif

org !ORG_ROOMNAMES+$96BA
  .Climb
if !FEATURE_ROOM_NAMES
    db $28, "Climb", $FF
endif

org !ORG_ROOMNAMES+$975C
  .PitRoom
if !FEATURE_ROOM_NAMES
    db $28, "Pit Room", $FF
endif

org !ORG_ROOMNAMES+$97B5
  .ElevToBlueBrinstar
if !FEATURE_ROOM_NAMES
    db $28, "Elev to Blue Brinstar", $FF
endif

org !ORG_ROOMNAMES+$9804
  .BombTorizoRoom
if !FEATURE_ROOM_NAMES
    db $28, "Bomb Torizo Room", $FF
endif

org !ORG_ROOMNAMES+$9879
  .Flyway
if !FEATURE_ROOM_NAMES
    db $28, "Flyway", $FF
endif

org !ORG_ROOMNAMES+$98E2
  .PreMapFlyway
if !FEATURE_ROOM_NAMES
    db $28, "Pre-Map Flyway", $FF
endif

org !ORG_ROOMNAMES+$990D
  .TerminatorRoom
if !FEATURE_ROOM_NAMES
    db $28, "Terminator Room", $FF
endif

org !ORG_ROOMNAMES+$9938
  .GreenBrinElevRoom
if !FEATURE_ROOM_NAMES
    db $28, "Green Brin Elev Room", $FF
endif

org !ORG_ROOMNAMES+$9969
  .LowerMushrooms
if !FEATURE_ROOM_NAMES
    db $28, "Lower Mushrooms", $FF
endif

org !ORG_ROOMNAMES+$9994
  .CrateriaMapRoom
if !FEATURE_ROOM_NAMES
    db $28, "Crateria Map Room", $FF
endif

org !ORG_ROOMNAMES+$99BD
  .GreenPiratesShaft
if !FEATURE_ROOM_NAMES
    db $28, "Green Pirates Shaft", $FF
endif

org !ORG_ROOMNAMES+$99F9
  .CrateriaSuperRoom
if !FEATURE_ROOM_NAMES
    db $28, "Crateria Super Room", $FF
endif

org !ORG_ROOMNAMES+$9A44
  .FinalMissileBombway
if !FEATURE_ROOM_NAMES
    db $28, "Final Missile Bombway", $FF
endif

org !ORG_ROOMNAMES+$9A90
  .TheFinalMissile
if !FEATURE_ROOM_NAMES
    db $28, "The Final Missile", $FF
endif

org !ORG_ROOMNAMES+$9AD9
  .GreenBrinMainShaft
if !FEATURE_ROOM_NAMES
    db $28, "Green Brin Main Shaft", $FF
endif

org !ORG_ROOMNAMES+$9B5B
  .SporeSpawnSuperRoom
if !FEATURE_ROOM_NAMES
    db $28, "Spore Spawn Super Room", $FF
endif

org !ORG_ROOMNAMES+$9B9D
  .BrinstarPreMapRoom
if !FEATURE_ROOM_NAMES
    db $28, "Brinstar Pre-Map Room", $FF
endif

org !ORG_ROOMNAMES+$9BC8
  .EarlySupersRoom
if !FEATURE_ROOM_NAMES
    db $28, "Early Supers Room", $FF
endif

org !ORG_ROOMNAMES+$9C07
  .BrinstarReserveTank
if !FEATURE_ROOM_NAMES
    db $28, "Brinstar Reserve Tank", $FF
endif

org !ORG_ROOMNAMES+$9C35
  .BrinstarMapRoom
if !FEATURE_ROOM_NAMES
    db $28, "Brinstar Map Room", $FF
endif

org !ORG_ROOMNAMES+$9C5E
  .GreenBrinFirefleas
if !FEATURE_ROOM_NAMES
    db $28, "Green Brin Firefleas", $FF
endif

org !ORG_ROOMNAMES+$9C89
  .GreenBrinMissileRefi
if !FEATURE_ROOM_NAMES
    db $28, "Green Brin Missile Refi", $FF
endif

org !ORG_ROOMNAMES+$9CB3
  .DachoraRoom
if !FEATURE_ROOM_NAMES
    db $28, "Dachora Room", $FF
endif

org !ORG_ROOMNAMES+$9D19
  .BigPink
if !FEATURE_ROOM_NAMES
    db $28, "Big Pink", $FF
endif

org !ORG_ROOMNAMES+$9D9C
  .SporeSpawnKihunters
if !FEATURE_ROOM_NAMES
    db $28, "Spore Spawn Kihunters", $FF
endif

org !ORG_ROOMNAMES+$9DC7
  .SporeSpawnRoom
if !FEATURE_ROOM_NAMES
    db $28, "Spore Spawn Room", $FF
endif

org !ORG_ROOMNAMES+$9E11
  .PinkBrinPowerBombs
if !FEATURE_ROOM_NAMES
    db $28, "Pink Brin Power Bombs", $FF
endif

org !ORG_ROOMNAMES+$9E52
  .GreenHillZone
if !FEATURE_ROOM_NAMES
    db $28, "Green Hill Zone", $FF
endif

org !ORG_ROOMNAMES+$9E9F
  .MorphBallRoom
if !FEATURE_ROOM_NAMES
    db $28, "Morph Ball Room", $FF
endif

org !ORG_ROOMNAMES+$9F11
  .ConstructionZone
if !FEATURE_ROOM_NAMES
    db $28, "Construction Zone", $FF
endif

org !ORG_ROOMNAMES+$9F64
  .BlueBrinstarETank
if !FEATURE_ROOM_NAMES
    db $28, "Blue Brinstar E-Tank", $FF
endif

org !ORG_ROOMNAMES+$9FBA
  .NoobBridge
if !FEATURE_ROOM_NAMES
    db $28, "Noob Bridge", $FF
endif

org !ORG_ROOMNAMES+$9FE5
  .GreenBrinstarBeetoms
if !FEATURE_ROOM_NAMES
    db $28, "Green Brinstar Beetoms", $FF
endif

org !ORG_ROOMNAMES+$A011
  .EtecoonETankRoom
if !FEATURE_ROOM_NAMES
    db $28, "Etecoon E-Tank Room", $FF
endif

org !ORG_ROOMNAMES+$A051
  .EtecoonSuperRoom
if !FEATURE_ROOM_NAMES
    db $28, "Etecoon Super Room", $FF
endif

org !ORG_ROOMNAMES+$A07B
  .DachoraEnergyRefill
if !FEATURE_ROOM_NAMES
    db $28, "Dachora Energy Refill", $FF
endif

org !ORG_ROOMNAMES+$A0A4
  .SporeSpawnFarming
if !FEATURE_ROOM_NAMES
    db $28, "Spore Spawn Farming", $FF
endif

org !ORG_ROOMNAMES+$A0D2
  .WaterwayETankRoom
if !FEATURE_ROOM_NAMES
    db $28, "Waterway E-Tank Room", $FF
endif

org !ORG_ROOMNAMES+$A107
  .FirstMissileRoom
if !FEATURE_ROOM_NAMES
    db $28, "First Missile Room", $FF
endif

org !ORG_ROOMNAMES+$A130
  .PinkBrinstarHoppers
if !FEATURE_ROOM_NAMES
    db $28, "Pink Brinstar Hoppers", $FF
endif

org !ORG_ROOMNAMES+$A15B
  .HopperEnergyTankRoom
if !FEATURE_ROOM_NAMES
    db $28, "Hopper Energy Tank Room", $FF
endif

org !ORG_ROOMNAMES+$A184
  .BigPinkSaveRoom
if !FEATURE_ROOM_NAMES
    db $28, "Big Pink Save Room", $FF
endif

org !ORG_ROOMNAMES+$A1AD
  .BlueBrinstarBoulders
if !FEATURE_ROOM_NAMES
    db $28, "Blue Brinstar Boulders", $FF
endif

org !ORG_ROOMNAMES+$A1D8
  .BillyMaysRoom
if !FEATURE_ROOM_NAMES
    db $28, "Billy Mays Room", $FF
endif

org !ORG_ROOMNAMES+$A201
  .GreenBrinSaveRoom
if !FEATURE_ROOM_NAMES
    db $28, "Green Brin Save Room", $FF
endif

org !ORG_ROOMNAMES+$A22A
  .EtecoonSaveRoom
if !FEATURE_ROOM_NAMES
    db $28, "Etecoon Save Room", $FF
endif

org !ORG_ROOMNAMES+$A253
  .RedTower
if !FEATURE_ROOM_NAMES
    db $28, "Red Tower", $FF
endif

org !ORG_ROOMNAMES+$A293
  .RedBrinstarFirefleas
if !FEATURE_ROOM_NAMES
    db $28, "Red Brinstar Firefleas", $FF
endif

org !ORG_ROOMNAMES+$A2CE
  .XRayScopeRoom
if !FEATURE_ROOM_NAMES
    db $28, "X-Ray Scope Room", $FF
endif

org !ORG_ROOMNAMES+$A2F7
  .Hellway
if !FEATURE_ROOM_NAMES
    db $28, "Hellway", $FF
endif

org !ORG_ROOMNAMES+$A322
  .CaterpillarRoom
if !FEATURE_ROOM_NAMES
    db $28, "Caterpillar Room", $FF
endif

org !ORG_ROOMNAMES+$A37C
  .BetaPowerBombRoom
if !FEATURE_ROOM_NAMES
    db $28, "Beta Power Bomb Room", $FF
endif

org !ORG_ROOMNAMES+$A3AE
  .AlphaPowerBombRoom
if !FEATURE_ROOM_NAMES
    db $28, "Alpha Power Bomb Room", $FF
endif

org !ORG_ROOMNAMES+$A3DD
  .SkreeBoostRoom
if !FEATURE_ROOM_NAMES
    db $28, "Skree Boost Room", $FF
endif

org !ORG_ROOMNAMES+$A408
  .BelowSpazer
if !FEATURE_ROOM_NAMES
    db $28, "Below Spazer", $FF
endif

org !ORG_ROOMNAMES+$A447
  .SpazerRoom
if !FEATURE_ROOM_NAMES
    db $28, "Spazer Room", $FF
endif

org !ORG_ROOMNAMES+$A471
  .WarehouseZeelaRoom
if !FEATURE_ROOM_NAMES
    db $28, "Warehouse Zeela Room", $FF
endif

org !ORG_ROOMNAMES+$A4B1
  .WarehouseETankRoom
if !FEATURE_ROOM_NAMES
    db $28, "Warehouse E-Tank Room", $FF
endif

org !ORG_ROOMNAMES+$A4DA
  .WarehouseKihunterRoom
if !FEATURE_ROOM_NAMES
    db $28, "Warehouse Kihunter Room", $FF
endif

org !ORG_ROOMNAMES+$A521
  .BabyKraidRoom
if !FEATURE_ROOM_NAMES
    db $28, "Baby Kraid Room", $FF
endif

org !ORG_ROOMNAMES+$A56B
  .KraidEyeDoorRoom
if !FEATURE_ROOM_NAMES
    db $28, "Kraid Eye Door Room", $FF
endif

org !ORG_ROOMNAMES+$A59F
  .KraidRoom
if !FEATURE_ROOM_NAMES
    db $28, "Kraid Room", $FF
endif

org !ORG_ROOMNAMES+$A5ED
  .StatuesHallway
if !FEATURE_ROOM_NAMES
    db $28, "Statues Hallway", $FF
endif

org !ORG_ROOMNAMES+$A618
  .SloatersRefill
if !FEATURE_ROOM_NAMES
    db $28, "Sloaters Refill", $FF
endif

org !ORG_ROOMNAMES+$A641
  .KraidRefillStations
if !FEATURE_ROOM_NAMES
    db $28, "Kraid Refill Stations", $FF
endif

org !ORG_ROOMNAMES+$A66A
  .StatuesRoom
if !FEATURE_ROOM_NAMES
    db $28, "Statues Room", $FF
endif

org !ORG_ROOMNAMES+$A6A1
  .WarehouseEntrance
if !FEATURE_ROOM_NAMES
    db $28, "Warehouse Entrance", $FF
endif

org !ORG_ROOMNAMES+$A6E2
  .VariaSuitRoom
if !FEATURE_ROOM_NAMES
    db $28, "Varia Suit Room", $FF
endif

org !ORG_ROOMNAMES+$A70B
  .WarehouseSaveRoom
if !FEATURE_ROOM_NAMES
    db $28, "Warehouse Save Room", $FF
endif

org !ORG_ROOMNAMES+$A734
  .RedBrinstarSaveRoom
if !FEATURE_ROOM_NAMES
    db $28, "Red Brinstar Save Room", $FF
endif

org !ORG_ROOMNAMES+$A75D
  .IceBeamAcidRoom
if !FEATURE_ROOM_NAMES
    db $28, "Ice Beam Acid Room", $FF
endif

org !ORG_ROOMNAMES+$A788
  .Cathedral
if !FEATURE_ROOM_NAMES
    db $28, "Cathedral", $FF
endif

org !ORG_ROOMNAMES+$A7B3
  .CathedralEntrance
if !FEATURE_ROOM_NAMES
    db $28, "Cathedral Entrance", $FF
endif

org !ORG_ROOMNAMES+$A7DE
  .BusinessCenter
if !FEATURE_ROOM_NAMES
    db $28, "Business Center", $FF
endif

org !ORG_ROOMNAMES+$A815
  .IceBeamGateRoom
if !FEATURE_ROOM_NAMES
    db $28, "Ice Beam Gate Room", $FF
endif

org !ORG_ROOMNAMES+$A865
  .IceBeamTutorialRoom
if !FEATURE_ROOM_NAMES
    db $28, "Ice Beam Tutorial Room", $FF
endif

org !ORG_ROOMNAMES+$A890
  .IceBeamRoom
if !FEATURE_ROOM_NAMES
    db $28, "Ice Beam Room", $FF
endif

org !ORG_ROOMNAMES+$A8B9
  .IceBeamSnakeRoom
if !FEATURE_ROOM_NAMES
    db $28, "Ice Beam Snake Room", $FF
endif

org !ORG_ROOMNAMES+$A8F8
  .CrumbleShaft
if !FEATURE_ROOM_NAMES
    db $28, "Crumble Shaft", $FF
endif

org !ORG_ROOMNAMES+$A923
  .CrocomireSpeedway
if !FEATURE_ROOM_NAMES
    db $28, "Crocomire Speedway", $FF
endif

org !ORG_ROOMNAMES+$A98D
  .CrocomireRoom
if !FEATURE_ROOM_NAMES
    db $28, "Crocomire's Room", $FF
endif

org !ORG_ROOMNAMES+$A9E5
  .HiJumpBootsRoom
if !FEATURE_ROOM_NAMES
    db $28, "Hi Jump Boots Room", $FF
endif

org !ORG_ROOMNAMES+$AA0E
  .CrocomireEscape
if !FEATURE_ROOM_NAMES
    db $28, "Crocomire Escape", $FF
endif

org !ORG_ROOMNAMES+$AA41
  .HiJumpETankRoom
if !FEATURE_ROOM_NAMES
    db $28, "Hi Jump E-Tank Room", $FF
endif

org !ORG_ROOMNAMES+$AA82
  .PostCrocFarmingRoom
if !FEATURE_ROOM_NAMES
    db $28, "Post Croc Farming Room", $FF
endif

org !ORG_ROOMNAMES+$AAB5
  .PostCrocSaveRoom
if !FEATURE_ROOM_NAMES
    db $28, "Post Croc Save Room", $FF
endif

org !ORG_ROOMNAMES+$AADE
  .PostCrocPowerBombs
if !FEATURE_ROOM_NAMES
    db $28, "Post Croc Power Bombs", $FF
endif

org !ORG_ROOMNAMES+$AB07
  .PostCrocomireShaft
if !FEATURE_ROOM_NAMES
    db $28, "Post Crocomire Shaft", $FF
endif

org !ORG_ROOMNAMES+$AB3B
  .PostCrocMissileRoom
if !FEATURE_ROOM_NAMES
    db $28, "Post Croc Missile Room", $FF
endif

org !ORG_ROOMNAMES+$AB64
  .GrappleTutorialRoom3
if !FEATURE_ROOM_NAMES
    db $28, "Grapple Tutorial Room 3", $FF
endif

org !ORG_ROOMNAMES+$AB8F
  .PostCrocJumpRoom
if !FEATURE_ROOM_NAMES
    db $28, "Post Croc Jump Room", $FF
endif

org !ORG_ROOMNAMES+$ABD2
  .GrappleTutorialRoom2
if !FEATURE_ROOM_NAMES
    db $28, "Grapple Tutorial Room 2", $FF
endif

org !ORG_ROOMNAMES+$AC00
  .GrappleTutorialRoom1
if !FEATURE_ROOM_NAMES
    db $28, "Grapple Tutorial Room 1", $FF
endif

org !ORG_ROOMNAMES+$AC2B
  .GrappleBeamRoom
if !FEATURE_ROOM_NAMES
    db $28, "Grapple Beam Room", $FF
endif

org !ORG_ROOMNAMES+$AC5A
  .NorfairReserveTank
if !FEATURE_ROOM_NAMES
    db $28, "Norfair Reserve Tank", $FF
endif

org !ORG_ROOMNAMES+$AC83
  .GreenBubblesMissiles
if !FEATURE_ROOM_NAMES
    db $28, "Green Bubbles Missiles", $FF
endif

org !ORG_ROOMNAMES+$ACB3
  .BubbleMountain
if !FEATURE_ROOM_NAMES
    db $28, "Bubble Mountain", $FF
endif

org !ORG_ROOMNAMES+$ACF0
  .SpeedBoosterHall
if !FEATURE_ROOM_NAMES
    db $28, "Speed Booster Hall", $FF
endif

org !ORG_ROOMNAMES+$AD1B
  .SpeedBoosterRoom
if !FEATURE_ROOM_NAMES
    db $28, "Speed Booster Room", $FF
endif

org !ORG_ROOMNAMES+$AD5E
  .SingleChamber
if !FEATURE_ROOM_NAMES
    db $28, "Single Chamber", $FF
endif

org !ORG_ROOMNAMES+$ADAD
  .DoubleChamber
if !FEATURE_ROOM_NAMES
    db $28, "Double Chamber", $FF
endif

org !ORG_ROOMNAMES+$ADDE
  .WaveBeamRoom
if !FEATURE_ROOM_NAMES
    db $28, "Wave Beam Room", $FF
endif

org !ORG_ROOMNAMES+$AE07
  .SpikyPlatformsTunnel
if !FEATURE_ROOM_NAMES
    db $28, "Spiky Platforms Tunnel", $FF
endif

org !ORG_ROOMNAMES+$AE32
  .VolcanoRoom
if !FEATURE_ROOM_NAMES
    db $28, "Volcano Room", $FF
endif

org !ORG_ROOMNAMES+$AE74
  .KronicBoostRoom
if !FEATURE_ROOM_NAMES
    db $28, "Kronic Boost Room", $FF
endif

org !ORG_ROOMNAMES+$AEB4
  .MagdolliteTunnel
if !FEATURE_ROOM_NAMES
    db $28, "Magdollite Tunnel", $FF
endif

org !ORG_ROOMNAMES+$AEDF
  .PurpleShaft
if !FEATURE_ROOM_NAMES
    db $28, "Purple Shaft", $FF
endif

org !ORG_ROOMNAMES+$AF14
  .LavaDiveRoom
if !FEATURE_ROOM_NAMES
    db $28, "Lava Dive Room", $FF
endif

org !ORG_ROOMNAMES+$AF3F
  .LowerNorfairElevator
if !FEATURE_ROOM_NAMES
    db $28, "Lower Norfair Elevator", $FF
endif

org !ORG_ROOMNAMES+$AF72
  .UpperNorfFarmingRoom
if !FEATURE_ROOM_NAMES
    db $28, "Upper Norf Farming Room", $FF
endif

org !ORG_ROOMNAMES+$AFA3
  .RisingTide
if !FEATURE_ROOM_NAMES
    db $28, "Rising Tide", $FF
endif

org !ORG_ROOMNAMES+$AFCE
  .AcidSnakesTunnel
if !FEATURE_ROOM_NAMES
    db $28, "Acid Snakes Tunnel", $FF
endif

org !ORG_ROOMNAMES+$AFFB
  .SpikyAcidSnakesTunnel
if !FEATURE_ROOM_NAMES
    db $28, "Spiky Acid Snakes Tunnel", $FF
endif

org !ORG_ROOMNAMES+$B026
  .NutellaRefill
if !FEATURE_ROOM_NAMES
    db $28, "Nutella Refill", $FF
endif

org !ORG_ROOMNAMES+$B051
  .PurpleFarmingRoom
if !FEATURE_ROOM_NAMES
    db $28, "Purple Farming Room", $FF
endif

org !ORG_ROOMNAMES+$B07A
  .BatCave
if !FEATURE_ROOM_NAMES
    db $28, "Bat Cave", $FF
endif

org !ORG_ROOMNAMES+$B0B4
  .NorfairMapRoom
if !FEATURE_ROOM_NAMES
    db $28, "Norfair Map Room", $FF
endif

org !ORG_ROOMNAMES+$B0DD
  .BubbleMountainSave
if !FEATURE_ROOM_NAMES
    db $28, "Bubble Mountain Save", $FF
endif

org !ORG_ROOMNAMES+$B106
  .FrogSpeedway
if !FEATURE_ROOM_NAMES
    db $28, "Frog Speedway", $FF
endif

org !ORG_ROOMNAMES+$B139
  .RedPirateShaft
if !FEATURE_ROOM_NAMES
    db $28, "Red Pirate Shaft", $FF
endif

org !ORG_ROOMNAMES+$B167
  .FrogSavestation
if !FEATURE_ROOM_NAMES
    db $28, "Frog Savestation", $FF
endif

org !ORG_ROOMNAMES+$B192
  .CrocomireSaveRoom
if !FEATURE_ROOM_NAMES
    db $28, "Crocomire Save Room", $FF
endif

org !ORG_ROOMNAMES+$B1BB
  .LNElevatorSaveRoom
if !FEATURE_ROOM_NAMES
    db $28, "LN Elevator Save Room", $FF
endif

org !ORG_ROOMNAMES+$B1E5
  .AcidStatueRoom
if !FEATURE_ROOM_NAMES
    db $28, "Acid Statue Room", $FF
endif

org !ORG_ROOMNAMES+$B236
  .MainHall
if !FEATURE_ROOM_NAMES
    db $28, "Main Hall", $FF
endif

org !ORG_ROOMNAMES+$B283
  .GoldenTorizoRoom
if !FEATURE_ROOM_NAMES
    db $28, "Golden Torizo's Room", $FF
endif

org !ORG_ROOMNAMES+$B2DA
  .FastRipperRoom
if !FEATURE_ROOM_NAMES
    db $28, "Fast Ripper Room", $FF
endif

org !ORG_ROOMNAMES+$B305
  .GTEnergyRecharge
if !FEATURE_ROOM_NAMES
    db $28, "GT Energy Recharge", $FF
endif

org !ORG_ROOMNAMES+$B32E
  .RidleyRoom
if !FEATURE_ROOM_NAMES
    db $28, "Ridley's Room", $FF
endif

org !ORG_ROOMNAMES+$B37A
  .LNFarmingRoom
if !FEATURE_ROOM_NAMES
    db $28, "LN Farming Room", $FF
endif

org !ORG_ROOMNAMES+$B3A5
  .FastPillarsSetupRoom
if !FEATURE_ROOM_NAMES
    db $28, "Fast Pillars Setup Room", $FF
endif

org !ORG_ROOMNAMES+$B40A
  .MickeyMouseRoom
if !FEATURE_ROOM_NAMES
    db $28, "Mickey Mouse Room", $FF
endif

org !ORG_ROOMNAMES+$B457
  .PillarRoom
if !FEATURE_ROOM_NAMES
    db $28, "Pillar Room", $FF
endif

org !ORG_ROOMNAMES+$B482
  .PlowerhouseRoom
if !FEATURE_ROOM_NAMES
    db $28, "Plowerhouse Room", $FF
endif

org !ORG_ROOMNAMES+$B4AD
  .WorstRoomInTheGame
if !FEATURE_ROOM_NAMES
    db $28, "Worst Room In The Game", $FF
endif

org !ORG_ROOMNAMES+$B4E5
  .Amphitheatre
if !FEATURE_ROOM_NAMES
    db $28, "Amphitheatre", $FF
endif

org !ORG_ROOMNAMES+$B510
  .LNSpringBallMaze
if !FEATURE_ROOM_NAMES
    db $28, "LN Spring Ball Maze", $FF
endif

org !ORG_ROOMNAMES+$B55A
  .LNEscapePowerBombs
if !FEATURE_ROOM_NAMES
    db $28, "LN Escape Power Bombs", $FF
endif

org !ORG_ROOMNAMES+$B585
  .RedKihunterShaft
if !FEATURE_ROOM_NAMES
    db $28, "Red Kihunter Shaft", $FF
endif

org !ORG_ROOMNAMES+$B5D5
  .Wasteland
if !FEATURE_ROOM_NAMES
    db $28, "Wasteland", $FF
endif

org !ORG_ROOMNAMES+$B62B
  .MetalPiratesRoom
if !FEATURE_ROOM_NAMES
    db $28, "Metal Pirates Room", $FF
endif

org !ORG_ROOMNAMES+$B656
  .ThreeMusketeersRoom
if !FEATURE_ROOM_NAMES
    db $28, "Three Musketeers' Room", $FF
endif

org !ORG_ROOMNAMES+$B698
  .RidleyTankRoom
if !FEATURE_ROOM_NAMES
    db $28, "Ridley Tank Room", $FF
endif

org !ORG_ROOMNAMES+$B6C1
  .ScrewAttackRoom
if !FEATURE_ROOM_NAMES
    db $28, "Screw Attack Room", $FF
endif

org !ORG_ROOMNAMES+$B6EE
  .LNFirefleaRoom
if !FEATURE_ROOM_NAMES
    db $28, "LN Fireflea Room", $FF
endif

org !ORG_ROOMNAMES+$B741
  .LowerNorfairSaveRoom
if !FEATURE_ROOM_NAMES
    db $28, "Lower Norfair Save Room", $FF
endif

org !ORG_ROOMNAMES+$C98E
  .BowlingAlley
if !FEATURE_ROOM_NAMES
    db $28, "Bowling Alley", $FF
endif

org !ORG_ROOMNAMES+$CA08
  .WreckedShipEntrance
if !FEATURE_ROOM_NAMES
    db $28, "Wrecked Ship Entrance", $FF
endif

org !ORG_ROOMNAMES+$CA52
  .Attic
if !FEATURE_ROOM_NAMES
    db $28, "Attic", $FF
endif

org !ORG_ROOMNAMES+$CAAE
  .AssemblyLine
if !FEATURE_ROOM_NAMES
    db $28, "Assembly Line", $FF
endif

org !ORG_ROOMNAMES+$CAF6
  .WreckedShipMainShaft
if !FEATURE_ROOM_NAMES
    db $28, "Wrecked Ship Main Shaft", $FF
endif

org !ORG_ROOMNAMES+$CB8B
  .SpikyDeathRoom
if !FEATURE_ROOM_NAMES
    db $28, "Spiky Death Room", $FF
endif

org !ORG_ROOMNAMES+$CBD5
  .ElectricDeathRoom
if !FEATURE_ROOM_NAMES
    db $28, "Electric Death Room", $FF
endif

org !ORG_ROOMNAMES+$CC27
  .WreckedShipETank
if !FEATURE_ROOM_NAMES
    db $28, "Wrecked Ship E-Tank", $FF
endif

org !ORG_ROOMNAMES+$CC6F
  .Basement
if !FEATURE_ROOM_NAMES
    db $28, "Basement", $FF
endif

org !ORG_ROOMNAMES+$CCCB
  .WreckedShipMapRoom
if !FEATURE_ROOM_NAMES
    db $28, "Wrecked Ship Map Room", $FF
endif

org !ORG_ROOMNAMES+$CD13
  .PhantoonRoom
if !FEATURE_ROOM_NAMES
    db $28, "Phantoon's Room", $FF
endif

org !ORG_ROOMNAMES+$CD5C
  .SpongeBath
if !FEATURE_ROOM_NAMES
    db $28, "Sponge Bath", $FF
endif

org !ORG_ROOMNAMES+$CDA8
  .WSWestSuperRoom
if !FEATURE_ROOM_NAMES
    db $28, "WS West Super Room", $FF
endif

org !ORG_ROOMNAMES+$CDF1
  .WSEastSuperRoom
if !FEATURE_ROOM_NAMES
    db $28, "WS East Super Room", $FF
endif

org !ORG_ROOMNAMES+$CE40
  .GravitySuitRoom
if !FEATURE_ROOM_NAMES
    db $28, "Gravity Suit Room", $FF
endif

org !ORG_ROOMNAMES+$CE8A
  .WreckedShipSaveRoom
if !FEATURE_ROOM_NAMES
    db $28, "Wrecked Ship Save Room", $FF
endif

org !ORG_ROOMNAMES+$CED2
  .GlassTunnelSaveRoom
if !FEATURE_ROOM_NAMES
    db $28, "Glass Tunnel Save Room", $FF
endif

org !ORG_ROOMNAMES+$CEFB
  .GlassTunnel
if !FEATURE_ROOM_NAMES
    db $28, "Glass Tunnel", $FF
endif

org !ORG_ROOMNAMES+$CF54
  .WestTunnel
if !FEATURE_ROOM_NAMES
    db $28, "West Tunnel", $FF
endif

org !ORG_ROOMNAMES+$CF80
  .EastTunnel
if !FEATURE_ROOM_NAMES
    db $28, "East Tunnel", $FF
endif

org !ORG_ROOMNAMES+$CFC9
  .MainStreet
if !FEATURE_ROOM_NAMES
    db $28, "Main Street", $FF
endif

org !ORG_ROOMNAMES+$D017
  .FishTank
if !FEATURE_ROOM_NAMES
    db $28, "Fish Tank", $FF
endif

org !ORG_ROOMNAMES+$D055
  .MamaTurtleRoom
if !FEATURE_ROOM_NAMES
    db $28, "Mama Turtle Room", $FF
endif

org !ORG_ROOMNAMES+$D08A
  .CrabTunnel
if !FEATURE_ROOM_NAMES
    db $28, "Crab Tunnel", $FF
endif

org !ORG_ROOMNAMES+$D0B9
  .MtEverest
if !FEATURE_ROOM_NAMES
    db $28, "Mt. Everest", $FF
endif

org !ORG_ROOMNAMES+$D104
  .RedFishRoom
if !FEATURE_ROOM_NAMES
    db $28, "Red Fish Room", $FF
endif

org !ORG_ROOMNAMES+$D13B
  .WateringHole
if !FEATURE_ROOM_NAMES
    db $28, "Watering Hole", $FF
endif

org !ORG_ROOMNAMES+$D16D
  .NWestMaridiaBugRoom
if !FEATURE_ROOM_NAMES
    db $28, "N.West Maridia Bug Room", $FF
endif

org !ORG_ROOMNAMES+$D1A3
  .CrabShaft
if !FEATURE_ROOM_NAMES
    db $28, "Crab Shaft", $FF
endif

org !ORG_ROOMNAMES+$D1DD
  .PseudoPlasmaSpark
if !FEATURE_ROOM_NAMES
    db $28, "Pseudo Plasma Spark", $FF
endif

org !ORG_ROOMNAMES+$D21C
  .CrabHole
if !FEATURE_ROOM_NAMES
    db $28, "Crab Hole", $FF
endif

org !ORG_ROOMNAMES+$D252
  .WestSandHallTunnel
if !FEATURE_ROOM_NAMES
    db $28, "West Sand Hall Tunnel", $FF
endif

org !ORG_ROOMNAMES+$D27E
  .PlasmaTutorialRoom
if !FEATURE_ROOM_NAMES
    db $28, "Plasma Tutorial Room", $FF
endif

org !ORG_ROOMNAMES+$D2AA
  .PlasmaRoom
if !FEATURE_ROOM_NAMES
    db $28, "Plasma Room", $FF
endif

org !ORG_ROOMNAMES+$D2D9
  .ThreadTheNeedleRoom
if !FEATURE_ROOM_NAMES
    db $28, "Thread The Needle Room", $FF
endif

org !ORG_ROOMNAMES+$D30B
  .MaridiaElevatorRoom
if !FEATURE_ROOM_NAMES
    db $28, "Maridia Elevator Room", $FF
endif

org !ORG_ROOMNAMES+$D340
  .PlasmaSparkRoom
if !FEATURE_ROOM_NAMES
    db $28, "Plasma Spark Room", $FF
endif

org !ORG_ROOMNAMES+$D387
  .KassiuzRoom
if !FEATURE_ROOM_NAMES
    db $28, "Kassiuz Room", $FF
endif

org !ORG_ROOMNAMES+$D3B6
  .MaridiaMapRoom
if !FEATURE_ROOM_NAMES
    db $28, "Maridia Map Room", $FF
endif

org !ORG_ROOMNAMES+$D3DF
  .ForgottenHighwaySave
if !FEATURE_ROOM_NAMES
    db $28, "Forgotten Highway Save", $FF
endif

org !ORG_ROOMNAMES+$D408
  .Toilet
if !FEATURE_ROOM_NAMES
    db $28, "Toilet", $FF
endif

org !ORG_ROOMNAMES+$D433
  .BugSandHole
if !FEATURE_ROOM_NAMES
    db $28, "Bug Sand Hole", $FF
endif

org !ORG_ROOMNAMES+$D461
  .WestSandHall
if !FEATURE_ROOM_NAMES
    db $28, "West Sand Hall", $FF
endif

org !ORG_ROOMNAMES+$D48E
  .Oasis
if !FEATURE_ROOM_NAMES
    db $28, "Oasis", $FF
endif

org !ORG_ROOMNAMES+$D4C2
  .EastSandHall
if !FEATURE_ROOM_NAMES
    db $28, "East Sand Hall", $FF
endif

org !ORG_ROOMNAMES+$D4EF
  .WestSandHole
if !FEATURE_ROOM_NAMES
    db $28, "West Sand Hole", $FF
endif

org !ORG_ROOMNAMES+$D51E
  .EastSandHole
if !FEATURE_ROOM_NAMES
    db $28, "East Sand Hole", $FF
endif

org !ORG_ROOMNAMES+$D54D
  .WestAqueductQuicksand
if !FEATURE_ROOM_NAMES
    db $28, "West Aqueduct Quicksand", $FF
endif

org !ORG_ROOMNAMES+$D57A
  .EastAqueductQuicksand
if !FEATURE_ROOM_NAMES
    db $28, "East Aqueduct Quicksand", $FF
endif

org !ORG_ROOMNAMES+$D5A7
  .Aqueduct
if !FEATURE_ROOM_NAMES
    db $28, "Aqueduct", $FF
endif

org !ORG_ROOMNAMES+$D5EC
  .ButterflyRoom
if !FEATURE_ROOM_NAMES
    db $28, "Butterfly Room", $FF
endif

org !ORG_ROOMNAMES+$D617
  .BotwoonHallway
if !FEATURE_ROOM_NAMES
    db $28, "Botwoon Hallway", $FF
endif

org !ORG_ROOMNAMES+$D646
  .PantsRoom
if !FEATURE_ROOM_NAMES
    db $28, "Pants Room", $FF
endif

org !ORG_ROOMNAMES+$D69A
  .EastPantsRoom
if !FEATURE_ROOM_NAMES
    db $28, "East Pants Room", $FF
endif

org !ORG_ROOMNAMES+$D6D0
  .SpringBallRoom
if !FEATURE_ROOM_NAMES
    db $28, "Spring Ball Room", $FF
endif

org !ORG_ROOMNAMES+$D6FD
  .BelowBotwoonETank
if !FEATURE_ROOM_NAMES
    db $28, "Below Botwoon E-Tank", $FF
endif

org !ORG_ROOMNAMES+$D72A
  .Colosseum
if !FEATURE_ROOM_NAMES
    db $28, "Colosseum", $FF
endif

org !ORG_ROOMNAMES+$D765
  .AqueductSaveRoom
if !FEATURE_ROOM_NAMES
    db $28, "Aqueduct Save Room", $FF
endif

org !ORG_ROOMNAMES+$D78F
  .ThePreciousRoom
if !FEATURE_ROOM_NAMES
    db $28, "The Precious Room", $FF
endif

org !ORG_ROOMNAMES+$D7E4
  .BotwoonETankRoom
if !FEATURE_ROOM_NAMES
    db $28, "Botwoon E-Tank Room", $FF
endif

org !ORG_ROOMNAMES+$D81A
  .DraygonSaveRoom
if !FEATURE_ROOM_NAMES
    db $28, "Draygon Save Room", $FF
endif

org !ORG_ROOMNAMES+$D845
  .MaridiaMissileRefill
if !FEATURE_ROOM_NAMES
    db $28, "Maridia Missile Refill", $FF
endif

org !ORG_ROOMNAMES+$D86E
  .PlasmaBeachQuicksand
if !FEATURE_ROOM_NAMES
    db $28, "Plasma Beach Quicksand", $FF
endif

org !ORG_ROOMNAMES+$D898
  .BotwoonQuicksandRoom
if !FEATURE_ROOM_NAMES
    db $28, "Botwoon Quicksand Room", $FF
endif

org !ORG_ROOMNAMES+$D8C5
  .ShaktoolRoom
if !FEATURE_ROOM_NAMES
    db $28, "Shaktool Room", $FF
endif

org !ORG_ROOMNAMES+$D913
  .HalfieClimbRoom
if !FEATURE_ROOM_NAMES
    db $28, "Halfie Climb Room", $FF
endif

org !ORG_ROOMNAMES+$D95E
  .BotwoonRoom
if !FEATURE_ROOM_NAMES
    db $28, "Botwoon's Room", $FF
endif

org !ORG_ROOMNAMES+$D9AA
  .SpaceJumpRoom
if !FEATURE_ROOM_NAMES
    db $28, "Space Jump Room", $FF
endif

org !ORG_ROOMNAMES+$D9D4
  .MaridiaEnergyRefill
if !FEATURE_ROOM_NAMES
    db $28, "Maridia Energy Refill", $FF
endif

org !ORG_ROOMNAMES+$D9FE
  .WestCactusAlleyRoom
if !FEATURE_ROOM_NAMES
    db $28, "West Cactus Alley Room", $FF
endif

org !ORG_ROOMNAMES+$DA2B
  .EastCactusAlleyRoom
if !FEATURE_ROOM_NAMES
    db $28, "East Cactus Alley Room", $FF
endif

org !ORG_ROOMNAMES+$DA60
  .DraygonRoom
if !FEATURE_ROOM_NAMES
    db $28, "Draygon's Room", $FF
endif

org !ORG_ROOMNAMES+$DAAE
  .TourianFirstRoom
if !FEATURE_ROOM_NAMES
    db $28, "Tourian First Room", $FF
endif

org !ORG_ROOMNAMES+$DAE1
  .MetroidRoom1
if !FEATURE_ROOM_NAMES
    db $28, "Metroid Room 1", $FF
endif

org !ORG_ROOMNAMES+$DB31
  .MetroidRoom2
if !FEATURE_ROOM_NAMES
    db $28, "Metroid Room 2", $FF
endif

org !ORG_ROOMNAMES+$DB7D
  .MetroidRoom3
if !FEATURE_ROOM_NAMES
    db $28, "Metroid Room 3", $FF
endif

org !ORG_ROOMNAMES+$DBCD
  .MetroidRoom4
if !FEATURE_ROOM_NAMES
    db $28, "Metroid Room 4", $FF
endif

org !ORG_ROOMNAMES+$DC19
  .BlueHopperRoom
if !FEATURE_ROOM_NAMES
    db $28, "Blue Hopper Room", $FF
endif

org !ORG_ROOMNAMES+$DC65
  .DustTorizoRoom
if !FEATURE_ROOM_NAMES
    db $28, "Dust Torizo Room", $FF
endif

org !ORG_ROOMNAMES+$DCB1
  .BigBoyRoom
if !FEATURE_ROOM_NAMES
    db $28, "Big Boy Room", $FF
endif

org !ORG_ROOMNAMES+$DCFF
  .SeaweedRoom
if !FEATURE_ROOM_NAMES
    db $28, "Seaweed Room", $FF
endif

org !ORG_ROOMNAMES+$DD2E
  .TourianRechargeRoom
if !FEATURE_ROOM_NAMES
    db $28, "Tourian Recharge Room", $FF
endif

org !ORG_ROOMNAMES+$DD58
  .MotherBrainRoom
if !FEATURE_ROOM_NAMES
    db $28, "Mother Brain Room", $FF
endif

org !ORG_ROOMNAMES+$DDC4
  .TourianEyeDoorRoom
if !FEATURE_ROOM_NAMES
    db $28, "Tourian Eye Door Room", $FF
endif

org !ORG_ROOMNAMES+$DDF3
  .RinkaShaft
if !FEATURE_ROOM_NAMES
    db $28, "Rinka Shaft", $FF
endif

org !ORG_ROOMNAMES+$DE23
  .MotherBrainSaveRoom
if !FEATURE_ROOM_NAMES
    db $28, "Mother Brain Save Room", $FF
endif

org !ORG_ROOMNAMES+$DE4D
  .TourianEscapeRoom1
if !FEATURE_ROOM_NAMES
    db $28, "Tourian Escape Room 1", $FF
endif

org !ORG_ROOMNAMES+$DE7A
  .TourianEscapeRoom2
if !FEATURE_ROOM_NAMES
    db $28, "Tourian Escape Room 2", $FF
endif

org !ORG_ROOMNAMES+$DEA7
  .TourianEscapeRoom3
if !FEATURE_ROOM_NAMES
    db $28, "Tourian Escape Room 3", $FF
endif

org !ORG_ROOMNAMES+$DEDE
  .TourianEscapeRoom4
if !FEATURE_ROOM_NAMES
    db $28, "Tourian Escape Room 4", $FF
endif

org !ORG_ROOMNAMES+$DF1B
  .UpperTourianSaveRoom
if !FEATURE_ROOM_NAMES
    db $28, "Upper Tourian Save Room", $FF
endif

org !ORG_ROOMNAMES+$DF45
  .CeresElevatorRoom
if !FEATURE_ROOM_NAMES
    db $28, "Ceres Elevator Room", $FF
endif

org !ORG_ROOMNAMES+$DF8D
  .FallingTileRoom
if !FEATURE_ROOM_NAMES
    db $28, "Falling Tile Room", $FF
endif

org !ORG_ROOMNAMES+$DFD7
  .MagnetStairsRoom
if !FEATURE_ROOM_NAMES
    db $28, "Magnet Stairs Room", $FF
endif

org !ORG_ROOMNAMES+$E021
  .DeadScientistRoom
if !FEATURE_ROOM_NAMES
    db $28, "Dead Scientist Room", $FF
endif

org !ORG_ROOMNAMES+$E06B
  .58Escape
if !FEATURE_ROOM_NAMES
    db $28, "58 Escape", $FF
endif

org !ORG_ROOMNAMES+$E0B5
  .CeresRidleyRoom
if !FEATURE_ROOM_NAMES
    db $28, "Ceres Ridley's Room", $FF
endif

org !ORG_ROOMNAMES+$E82C
  .DebugRoom
if !FEATURE_ROOM_NAMES
    db $28, "Debug Room", $FF
endif

if !FEATURE_ROOM_NAMES
print pc, " roomnames end"
endif

